export const CCM_PRICING_TIERS = [
  {
    name: "CCM Starter",
    slug: "ccm-starter",
    price: 499,
    interval: "month" as const,
    description: "For companies beginning their continuous monitoring journey",
    features: [
      "1 ERP connector (SAP or Mock)",
      "Up to 5 team members",
      "25 monitoring rules",
      "100 AI analyses per month",
      "SOX framework support",
      "12-hour sync frequency",
      "1 GB evidence storage",
      "90-day audit log retention",
      "DeepSeek LLM included",
      "Email support",
    ],
    excludedFeatures: [
      "Multi-framework support",
      "Custom monitoring rules",
      "Real-time sync",
      "BYOK (custom LLM provider)",
      "Dedicated account manager",
    ],
    envPriceKey: "STRIPE_PRICE_CCM_STARTER",
  },
  {
    name: "CCM Professional",
    slug: "ccm-professional",
    price: 1499,
    interval: "month" as const,
    description: "For organizations with complex compliance requirements",
    popular: true,
    features: [
      "Up to 3 ERP connectors",
      "Up to 15 team members",
      "100 monitoring rules",
      "500 AI analyses per month",
      "SOX + PCI DSS + AML frameworks",
      "4-hour sync frequency",
      "10 GB evidence storage",
      "1-year audit log retention",
      "BYOK — any LLM provider",
      "Custom monitoring rules",
      "Priority support",
    ],
    excludedFeatures: [
      "Unlimited connectors",
      "Real-time sync",
      "Dedicated account manager",
    ],
    envPriceKey: "STRIPE_PRICE_CCM_PRO",
  },
  {
    name: "CCM Enterprise",
    slug: "ccm-enterprise",
    price: 4999,
    interval: "month" as const,
    description: "For large enterprises requiring full continuous controls monitoring",
    features: [
      "Unlimited ERP connectors",
      "Unlimited team members",
      "Unlimited monitoring rules",
      "Unlimited AI analyses",
      "All frameworks (SOX, PCI, HIPAA, AML, GDPR, ISO, NIST)",
      "1-hour sync + real-time events",
      "100 GB evidence storage",
      "7-year audit log retention",
      "BYOK — any LLM + self-hosted",
      "Custom monitoring rules",
      "Automated remediation workflows",
      "Dedicated Customer Success Manager",
      "SLA guarantee (99.9% uptime)",
    ],
    excludedFeatures: [],
    envPriceKey: "STRIPE_PRICE_CCM_ENTERPRISE",
  },
] as const;

export const CCM_CONNECTOR_TYPES = [
  {
    type: "SAP_S4HANA_CLOUD",
    label: "SAP S/4HANA Cloud",
    description: "Connect to SAP S/4HANA Cloud via OData V4 APIs",
    available: true,
  },
  {
    type: "SAP_S4HANA_ONPREM",
    label: "SAP S/4HANA On-Premise",
    description: "Connect to on-premise SAP via Cloud Connector or VPN",
    available: true,
  },
  {
    type: "SAP_ECC",
    label: "SAP ECC 6.0",
    description: "Connect to legacy SAP ECC via OData or RFC",
    available: true,
  },
  {
    type: "MOCK",
    label: "Demo / Mock",
    description: "Simulated connector with realistic compliance data for testing",
    available: true,
  },
  {
    type: "ORACLE_CLOUD",
    label: "Oracle ERP Cloud",
    description: "Connect to Oracle Fusion ERP Cloud",
    available: false,
    comingSoon: "Q3 2026",
  },
  {
    type: "WORKDAY",
    label: "Workday",
    description: "Connect to Workday Financial Management & HCM",
    available: false,
    comingSoon: "Q3 2026",
  },
  {
    type: "CONCUR",
    label: "SAP Concur",
    description: "Connect to SAP Concur for T&E compliance",
    available: false,
    comingSoon: "Q4 2026",
  },
  {
    type: "DYNAMICS_365",
    label: "Microsoft Dynamics 365",
    description: "Connect to Dynamics 365 Finance & Operations",
    available: false,
    comingSoon: "Q1 2027",
  },
  {
    type: "NETSUITE",
    label: "Oracle NetSuite",
    description: "Connect to NetSuite ERP for mid-market compliance",
    available: false,
    comingSoon: "Q2 2027",
  },
] as const;
