import { PrismaClient } from "@prisma/client";

const db = new PrismaClient();

const hrVendors = [
  {
    name: "ADP",
    slug: "adp",
    description:
      "ADP is one of the world's largest providers of human capital management (HCM) solutions, serving over 1 million clients across 140 countries. Their comprehensive platform covers payroll processing, tax compliance, benefits administration, time and attendance, talent management, and HR compliance. ADP's DataCloud provides workforce analytics and benchmarking powered by anonymized data from 30+ million employees. Their compliance engine automatically tracks federal, state, and local labor law changes across all US jurisdictions, including pay transparency requirements, wage and hour rules, and employment tax updates. ADP TotalSource offers a full PEO solution for small and mid-size businesses needing complete HR outsourcing with built-in compliance.",
    shortDescription: "Global HCM, payroll, tax compliance, and workforce management for enterprises of all sizes",
    websiteUrl: "https://www.adp.com",
    category: "HR_COMPLIANCE" as const,
    subcategories: ["payroll", "tax-compliance", "benefits-administration", "workforce-analytics", "hcm"],
    pricingModel: "CONTACT_SALES" as const,
    pricingStartsAt: "Custom",
    pricingDetails: "Pricing varies by company size and modules. RUN (1-49 employees) starts ~$79/mo + $4/employee. Workforce Now (50-999) is custom. Enterprise (1000+) is custom.",
    hasFreeTrialOrTier: false,
    frameworksSupported: ["SOC 2", "SOC 1", "ISO 27001", "GDPR", "CCPA", "FLSA", "ACA"],
    deploymentsSupported: ["cloud", "hybrid"],
    integrationsSupported: ["SAP", "Oracle", "Workday", "QuickBooks", "Salesforce", "NetSuite"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: true,
    overallScore: 8.5,
    easeOfUse: 7.5,
    featureRichness: 9.5,
    valueForMoney: 7.0,
    customerSupport: 7.5,
    companySize: "Enterprise",
    foundedYear: 1949,
    headquarters: "Roseland, NJ, USA",
    employeeCount: "60000+",
    isPublished: true,
    isFeatured: true,
  },
  {
    name: "Deel",
    slug: "deel",
    description:
      "Deel is a global payroll and compliance platform that enables companies to hire and pay employees and contractors in 150+ countries without setting up local entities. Their Employer of Record (EOR) service handles employment contracts, benefits, tax withholding, and labor law compliance in each jurisdiction. Deel automatically generates locally compliant contracts, manages visa and work permit applications, handles equity compensation across borders, and provides real-time compliance updates. Their platform includes built-in compliance with local employment laws, statutory benefits, termination procedures, and data privacy regulations including GDPR. Deel Shield offers contractor misclassification protection and compliance insurance.",
    shortDescription: "Global payroll, EOR, contractor management, and cross-border compliance in 150+ countries",
    websiteUrl: "https://www.deel.com",
    category: "HR_COMPLIANCE" as const,
    subcategories: ["global-payroll", "eor", "contractor-management", "immigration", "compliance"],
    pricingModel: "PER_SEAT" as const,
    pricingStartsAt: "$49/contractor/mo",
    pricingDetails: "Contractors from $49/mo. EOR from $599/employee/mo. Global Payroll from $29/employee/mo. Deel HR is free.",
    hasFreeTrialOrTier: true,
    frameworksSupported: ["SOC 2", "ISO 27001", "GDPR", "CCPA"],
    deploymentsSupported: ["cloud"],
    integrationsSupported: ["QuickBooks", "Xero", "NetSuite", "BambooHR", "Greenhouse", "Workday"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: true,
    overallScore: 8.8,
    easeOfUse: 9.0,
    featureRichness: 9.0,
    valueForMoney: 8.0,
    customerSupport: 8.5,
    companySize: "Startup to Enterprise",
    foundedYear: 2019,
    headquarters: "San Francisco, CA, USA",
    employeeCount: "4000+",
    isPublished: true,
    isFeatured: true,
  },
  {
    name: "Rippling",
    slug: "rippling",
    description:
      "Rippling is a unified workforce management platform that combines HR, IT, and Finance into a single system. Their HR Cloud includes payroll processing across all 50 US states and 50+ countries, benefits administration, time and attendance, talent management, and compliance. Rippling's compliance engine automatically enforces federal, state, and local labor laws including overtime rules, meal and rest break requirements, and pay transparency obligations. Their IT Cloud manages device and app provisioning tied to employee lifecycle events. The platform offers automated tax registration, ACA compliance, and built-in enforcement of employment laws with configurable compliance policies that can be customized per jurisdiction and role.",
    shortDescription: "Unified HR, IT, and Finance platform with automated compliance enforcement",
    websiteUrl: "https://www.rippling.com",
    category: "HR_COMPLIANCE" as const,
    subcategories: ["hris", "payroll", "benefits", "it-management", "compliance-automation"],
    pricingModel: "PER_SEAT" as const,
    pricingStartsAt: "$8/user/mo",
    pricingDetails: "Starts at $8/user/month for core platform. Additional modules priced separately. Custom pricing for enterprise.",
    hasFreeTrialOrTier: false,
    frameworksSupported: ["SOC 2", "SOC 1", "GDPR", "CCPA", "FLSA", "ACA"],
    deploymentsSupported: ["cloud"],
    integrationsSupported: ["Slack", "Google Workspace", "Microsoft 365", "QuickBooks", "Salesforce", "Jira"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: false,
    overallScore: 8.7,
    easeOfUse: 9.0,
    featureRichness: 9.0,
    valueForMoney: 8.5,
    customerSupport: 8.0,
    companySize: "SMB to Enterprise",
    foundedYear: 2016,
    headquarters: "San Francisco, CA, USA",
    employeeCount: "3000+",
    isPublished: true,
    isFeatured: true,
  },
  {
    name: "Syndio",
    slug: "syndio",
    description:
      "Syndio is a workplace equity analytics platform that helps organizations measure, achieve, and sustain pay equity and opportunity equity. Their PayEQ product uses statistical analysis to identify pay disparities across gender, race, ethnicity, and other protected characteristics, providing remediation recommendations and ongoing monitoring. OppEQ analyzes representation, hiring, promotion, and retention patterns to identify systemic equity gaps. Syndio's platform helps organizations comply with pay transparency laws including the EU Pay Transparency Directive (2023/970), California SB 1162, NYC Local Law 32, and Colorado Equal Pay Act. The platform generates audit-ready documentation and supports proactive pay equity adjustments before regulatory deadlines.",
    shortDescription: "Pay equity analytics, compensation analysis, and workplace equity compliance platform",
    websiteUrl: "https://www.syndio.com",
    category: "PAY_EQUITY" as const,
    subcategories: ["pay-equity", "compensation-analytics", "dei", "compliance", "workforce-analytics"],
    pricingModel: "CONTACT_SALES" as const,
    pricingStartsAt: "Custom",
    pricingDetails: "Custom pricing based on employee count and modules selected. Enterprise-focused.",
    hasFreeTrialOrTier: false,
    frameworksSupported: ["EEOC", "OFCCP", "EU Pay Transparency Directive", "GDPR"],
    deploymentsSupported: ["cloud"],
    integrationsSupported: ["Workday", "SAP SuccessFactors", "ADP", "Oracle HCM", "UKG"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: false,
    overallScore: 8.5,
    easeOfUse: 8.0,
    featureRichness: 9.0,
    valueForMoney: 7.5,
    customerSupport: 8.5,
    companySize: "Enterprise",
    foundedYear: 2017,
    headquarters: "Seattle, WA, USA",
    employeeCount: "200+",
    isPublished: true,
    isFeatured: false,
  },
  {
    name: "Remote",
    slug: "remote-hr",
    description:
      "Remote is a global employment platform that enables companies to hire full-time employees and contractors in 75+ countries without establishing local entities. Their EOR service handles all aspects of international employment including locally compliant contracts, payroll, benefits, tax withholding, and statutory contributions. Remote's IP Guard ensures companies retain full ownership of intellectual property created by remote workers in any jurisdiction. The platform manages complex compliance requirements including severance calculations, probation periods, notice requirements, and statutory leave entitlements. Remote also offers contractor management with automatic classification analysis, reducing misclassification risk. Their compliance team monitors regulatory changes across all supported countries.",
    shortDescription: "Global EOR, contractor management, and international payroll with IP protection",
    websiteUrl: "https://www.remote.com",
    category: "HR_COMPLIANCE" as const,
    subcategories: ["eor", "global-payroll", "contractor-management", "ip-protection", "compliance"],
    pricingModel: "PER_SEAT" as const,
    pricingStartsAt: "$29/contractor/mo",
    pricingDetails: "Contractor Management from $29/mo. EOR from $599/employee/mo. Global Payroll from $50/employee/mo.",
    hasFreeTrialOrTier: false,
    frameworksSupported: ["SOC 2", "ISO 27001", "GDPR", "CCPA"],
    deploymentsSupported: ["cloud"],
    integrationsSupported: ["BambooHR", "Greenhouse", "Lever", "Bob", "Workday", "NetSuite"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: true,
    overallScore: 8.3,
    easeOfUse: 8.5,
    featureRichness: 8.5,
    valueForMoney: 8.0,
    customerSupport: 8.0,
    companySize: "Startup to Enterprise",
    foundedYear: 2019,
    headquarters: "San Francisco, CA, USA",
    employeeCount: "1500+",
    isPublished: true,
    isFeatured: false,
  },
  {
    name: "Papaya Global",
    slug: "papaya-global",
    description:
      "Papaya Global is a global workforce payments and payroll platform that processes payments in 160+ countries. Their platform combines payroll technology with a network of local payroll providers, offering both SaaS payroll management and a fully managed payroll service. Papaya's compliance engine handles tax calculations, statutory deductions, and labor law requirements for each jurisdiction. The platform offers real-time workforce analytics, cost projections, and compliance risk scoring. Their embedded payments infrastructure enables same-day payments across borders. Papaya also provides EOR services, contractor payments, and immigration support. SOX compliance reporting and multi-entity consolidation make it suitable for publicly traded companies.",
    shortDescription: "Global workforce payments, payroll, and compliance platform in 160+ countries",
    websiteUrl: "https://www.papayaglobal.com",
    category: "HR_COMPLIANCE" as const,
    subcategories: ["global-payroll", "payments", "eor", "compliance", "workforce-analytics"],
    pricingModel: "PER_SEAT" as const,
    pricingStartsAt: "$3/payslip",
    pricingDetails: "Payroll Platform from $3/payslip. Full Service Payroll from $12/payslip. EOR from $650/employee/mo.",
    hasFreeTrialOrTier: false,
    frameworksSupported: ["SOC 1", "SOC 2", "ISO 27001", "GDPR", "SOX"],
    deploymentsSupported: ["cloud"],
    integrationsSupported: ["SAP", "Oracle", "Workday", "NetSuite", "BambooHR", "ADP"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: true,
    overallScore: 8.2,
    easeOfUse: 8.0,
    featureRichness: 8.5,
    valueForMoney: 7.5,
    customerSupport: 8.0,
    companySize: "Mid-Market to Enterprise",
    foundedYear: 2016,
    headquarters: "New York, NY, USA",
    employeeCount: "1000+",
    isPublished: true,
    isFeatured: false,
  },
  {
    name: "Gusto",
    slug: "gusto",
    description:
      "Gusto is a modern HR platform built for small and medium-sized businesses, offering payroll, benefits, time tracking, and compliance tools. Their platform handles multi-state payroll processing with automated tax calculations, filings, and payments for all 50 US states. Gusto provides health insurance, 401(k), workers' compensation, and other benefits administration. Their compliance features include automated labor law poster distribution, new hire reporting, ACA compliance tracking, and pay transparency compliance. Gusto's embedded payroll product allows other software companies to offer payroll through their platforms. The system generates W-2s, 1099s, and other tax documents automatically, and handles garnishments and deductions.",
    shortDescription: "Modern payroll, benefits, and HR compliance platform for small businesses",
    websiteUrl: "https://www.gusto.com",
    category: "HR_COMPLIANCE" as const,
    subcategories: ["payroll", "benefits", "compliance", "time-tracking", "hiring"],
    pricingModel: "SUBSCRIPTION" as const,
    pricingStartsAt: "$40/mo + $6/person",
    pricingDetails: "Simple: $40/mo + $6/person. Plus: $80/mo + $12/person. Premium: $180/mo + $22/person.",
    hasFreeTrialOrTier: false,
    frameworksSupported: ["SOC 2", "FLSA", "ACA", "CCPA"],
    deploymentsSupported: ["cloud"],
    integrationsSupported: ["QuickBooks", "Xero", "FreshBooks", "Clover", "Shopify", "Square"],
    hasDPA: true,
    gdprCompliant: false,
    soc2Certified: true,
    iso27001Certified: false,
    overallScore: 8.5,
    easeOfUse: 9.5,
    featureRichness: 7.5,
    valueForMoney: 8.5,
    customerSupport: 8.0,
    companySize: "Small Business",
    foundedYear: 2011,
    headquarters: "San Francisco, CA, USA",
    employeeCount: "2500+",
    isPublished: true,
    isFeatured: false,
  },
  {
    name: "BambooHR",
    slug: "bamboohr",
    description:
      "BambooHR is a cloud-based HR information system (HRIS) designed for small and medium-sized businesses. The platform provides employee data management, hiring and onboarding, time tracking, PTO management, performance management, and employee satisfaction surveys. BambooHR's reporting and analytics engine generates compliance reports for EEO-1, ACA, and other regulatory requirements. Their benefits administration module handles open enrollment, carrier connections, and COBRA compliance. The platform includes electronic signatures for HR documents, customizable workflows for approvals, and an employee self-service portal. BambooHR's mobile app provides on-the-go access to HR functions for both employees and managers.",
    shortDescription: "HRIS for small and medium businesses with payroll, benefits, and compliance reporting",
    websiteUrl: "https://www.bamboohr.com",
    category: "HR_COMPLIANCE" as const,
    subcategories: ["hris", "hiring", "onboarding", "performance", "compliance-reporting"],
    pricingModel: "PER_SEAT" as const,
    pricingStartsAt: "$5.25/employee/mo",
    pricingDetails: "Core plan from $5.25/employee/mo. Pro plan from $8.75/employee/mo. Add-on modules available.",
    hasFreeTrialOrTier: true,
    frameworksSupported: ["SOC 2", "FLSA", "ACA", "CCPA", "EEO-1"],
    deploymentsSupported: ["cloud"],
    integrationsSupported: ["Slack", "Google Workspace", "Microsoft 365", "Greenhouse", "Indeed", "Checkr"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: false,
    overallScore: 8.3,
    easeOfUse: 9.0,
    featureRichness: 7.5,
    valueForMoney: 8.0,
    customerSupport: 8.5,
    companySize: "SMB",
    foundedYear: 2008,
    headquarters: "Lindon, UT, USA",
    employeeCount: "1500+",
    isPublished: true,
    isFeatured: false,
  },
  {
    name: "Workday HCM",
    slug: "workday-hcm",
    description:
      "Workday Human Capital Management (HCM) is an enterprise-grade cloud platform that unifies HR, talent, payroll, and workforce planning. The platform serves over 60% of Fortune 500 companies with capabilities spanning core HR, recruiting, learning, compensation, benefits, absence management, and analytics. Workday's global payroll supports 50+ countries with localized compliance for tax, social security, and labor regulations. Their AI-powered Skills Cloud enables skills-based talent strategies, while Workday Peakon provides continuous employee listening and engagement analytics. The platform's compliance features include automated regulatory reporting, configurable business process frameworks, and audit trail capabilities. Workday VIBE (Value Inclusion, Belonging, and Equity) provides DEI analytics and pay equity reporting.",
    shortDescription: "Enterprise HCM platform with global payroll, talent management, and workforce analytics",
    websiteUrl: "https://www.workday.com",
    category: "HR_COMPLIANCE" as const,
    subcategories: ["hcm", "global-payroll", "talent-management", "workforce-planning", "dei-analytics"],
    pricingModel: "CONTACT_SALES" as const,
    pricingStartsAt: "Custom",
    pricingDetails: "Enterprise pricing only. Typically $100-$300+ per employee per year depending on modules and company size.",
    hasFreeTrialOrTier: false,
    frameworksSupported: ["SOC 1", "SOC 2", "ISO 27001", "ISO 27018", "GDPR", "CCPA", "FedRAMP"],
    deploymentsSupported: ["cloud"],
    integrationsSupported: ["Salesforce", "ServiceNow", "Microsoft Teams", "Slack", "SAP", "Oracle"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: true,
    overallScore: 8.8,
    easeOfUse: 7.0,
    featureRichness: 9.5,
    valueForMoney: 6.5,
    customerSupport: 8.0,
    companySize: "Enterprise",
    foundedYear: 2005,
    headquarters: "Pleasanton, CA, USA",
    employeeCount: "18000+",
    isPublished: true,
    isFeatured: true,
  },
  {
    name: "UKG (Ultimate Kronos Group)",
    slug: "ukg",
    description:
      "UKG is a leading provider of HR, payroll, workforce management, and culture solutions formed from the merger of Ultimate Software and Kronos. UKG Pro delivers comprehensive HCM including payroll, benefits, talent management, and employee surveys. UKG Ready provides HR and payroll for mid-market organizations. UKG Dimensions offers advanced workforce management with AI-powered scheduling, time tracking, and labor compliance. The platform's compliance engine covers wage and hour regulations across all US states and 30+ countries, including predictive scheduling laws, overtime rules, meal and rest break requirements, and minor labor laws. UKG's Great Place To Work culture analytics provide workplace culture assessment and benchmarking.",
    shortDescription: "Enterprise HCM, workforce management, and labor compliance platform",
    websiteUrl: "https://www.ukg.com",
    category: "HR_COMPLIANCE" as const,
    subcategories: ["hcm", "workforce-management", "payroll", "time-attendance", "labor-compliance"],
    pricingModel: "CONTACT_SALES" as const,
    pricingStartsAt: "Custom",
    pricingDetails: "Custom pricing based on modules and employee count. Serves mid-market to enterprise.",
    hasFreeTrialOrTier: false,
    frameworksSupported: ["SOC 1", "SOC 2", "ISO 27001", "GDPR", "FLSA", "ACA"],
    deploymentsSupported: ["cloud"],
    integrationsSupported: ["SAP", "Oracle", "Workday", "Microsoft Teams", "Salesforce", "ServiceNow"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: true,
    overallScore: 8.4,
    easeOfUse: 7.0,
    featureRichness: 9.0,
    valueForMoney: 7.0,
    customerSupport: 8.0,
    companySize: "Mid-Market to Enterprise",
    foundedYear: 2020,
    headquarters: "Lowell, MA, USA",
    employeeCount: "15000+",
    isPublished: true,
    isFeatured: false,
  },
  {
    name: "Paylocity",
    slug: "paylocity",
    description:
      "Paylocity is a cloud-based payroll and HCM platform serving mid-market organizations. Their platform includes payroll processing, tax services, HR management, benefits administration, time and labor management, talent management, and employee experience tools. Paylocity's compliance features include automated tax filing in all 50 states, ACA reporting, EEO-1 filing, OSHA reporting, and garnishment management. Their Community social collaboration tool enhances employee engagement. The platform offers advanced reporting and analytics, configurable workflows, and mobile-first employee self-service. Paylocity's On Demand Payment feature allows employees to access earned wages before payday, supporting financial wellness compliance.",
    shortDescription: "Cloud payroll, HR, and talent management for mid-market companies",
    websiteUrl: "https://www.paylocity.com",
    category: "HR_COMPLIANCE" as const,
    subcategories: ["payroll", "hcm", "benefits", "talent-management", "compliance"],
    pricingModel: "PER_SEAT" as const,
    pricingStartsAt: "Custom",
    pricingDetails: "Custom pricing based on modules and employee count. Typically serves 50-5000+ employees.",
    hasFreeTrialOrTier: false,
    frameworksSupported: ["SOC 1", "SOC 2", "ISO 27001", "FLSA", "ACA", "EEO-1"],
    deploymentsSupported: ["cloud"],
    integrationsSupported: ["QuickBooks", "NetSuite", "Salesforce", "Greenhouse", "Indeed", "LinkedIn"],
    hasDPA: true,
    gdprCompliant: false,
    soc2Certified: true,
    iso27001Certified: true,
    overallScore: 8.2,
    easeOfUse: 8.0,
    featureRichness: 8.5,
    valueForMoney: 8.0,
    customerSupport: 8.0,
    companySize: "Mid-Market",
    foundedYear: 1997,
    headquarters: "Schaumburg, IL, USA",
    employeeCount: "6000+",
    isPublished: true,
    isFeatured: false,
  },
  {
    name: "Paychex",
    slug: "paychex",
    description:
      "Paychex is a major provider of payroll, HR, and benefits outsourcing solutions, serving over 740,000 clients primarily in the small to mid-sized business segment. Their Paychex Flex platform offers payroll processing, tax administration, HR administration, employee benefits, retirement services, insurance, and compliance solutions. Paychex's compliance services include automated tax filing and deposits, ACA compliance, pay transparency compliance, wage garnishment processing, and new hire reporting. Their HR advisory services provide dedicated HR professionals who help businesses navigate complex employment laws. Paychex PEO (Professional Employer Organization) offers co-employment for comprehensive HR outsourcing with shared employer liability.",
    shortDescription: "Payroll, HR, and benefits outsourcing with compliance advisory for SMBs",
    websiteUrl: "https://www.paychex.com",
    category: "HR_COMPLIANCE" as const,
    subcategories: ["payroll", "peo", "benefits", "retirement", "compliance-advisory"],
    pricingModel: "CONTACT_SALES" as const,
    pricingStartsAt: "$39/mo + $5/employee",
    pricingDetails: "Essentials from $39/mo + $5/employee. Select from $59/mo + $6/employee. Pro from custom pricing.",
    hasFreeTrialOrTier: false,
    frameworksSupported: ["SOC 1", "FLSA", "ACA", "EEO-1", "OSHA"],
    deploymentsSupported: ["cloud"],
    integrationsSupported: ["QuickBooks", "Xero", "Sage", "Microsoft 365", "Clover", "Indeed"],
    hasDPA: true,
    gdprCompliant: false,
    soc2Certified: true,
    iso27001Certified: false,
    overallScore: 8.0,
    easeOfUse: 8.0,
    featureRichness: 8.0,
    valueForMoney: 7.5,
    customerSupport: 8.5,
    companySize: "SMB to Mid-Market",
    foundedYear: 1971,
    headquarters: "Rochester, NY, USA",
    employeeCount: "16000+",
    isPublished: true,
    isFeatured: false,
  },
];

async function main() {
  console.log(`Seeding ${hrVendors.length} HR compliance vendors...`);

  for (const vendor of hrVendors) {
    await db.vendor.upsert({
      where: { slug: vendor.slug },
      update: {
        name: vendor.name,
        description: vendor.description,
        shortDescription: vendor.shortDescription,
        websiteUrl: vendor.websiteUrl,
        category: vendor.category,
        subcategories: vendor.subcategories,
        pricingModel: vendor.pricingModel,
        pricingStartsAt: vendor.pricingStartsAt,
        pricingDetails: vendor.pricingDetails,
        hasFreeTrialOrTier: vendor.hasFreeTrialOrTier,
        frameworksSupported: vendor.frameworksSupported,
        deploymentsSupported: vendor.deploymentsSupported,
        integrationsSupported: vendor.integrationsSupported,
        hasDPA: vendor.hasDPA,
        gdprCompliant: vendor.gdprCompliant,
        soc2Certified: vendor.soc2Certified,
        iso27001Certified: vendor.iso27001Certified,
        overallScore: vendor.overallScore,
        easeOfUse: vendor.easeOfUse,
        featureRichness: vendor.featureRichness,
        valueForMoney: vendor.valueForMoney,
        customerSupport: vendor.customerSupport,
        companySize: vendor.companySize,
        foundedYear: vendor.foundedYear,
        headquarters: vendor.headquarters,
        employeeCount: vendor.employeeCount,
        isPublished: vendor.isPublished,
        isFeatured: vendor.isFeatured,
      },
      create: vendor,
    });
    console.log(`  ✓ ${vendor.name}`);
  }

  console.log(`\nDone! ${hrVendors.length} HR vendors seeded.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await db.$disconnect();
  });
