import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const db = new PrismaClient();

async function main() {
  console.log("Seeding database...");

  // Create admin user
  const hashedPassword = await bcrypt.hash("Admin2026!", 12);
  const admin = await db.user.upsert({
    where: { email: "admin@aigovhub.com" },
    update: {},
    create: {
      email: "admin@aigovhub.com",
      name: "Admin",
      hashedPassword,
      role: "SUPER_ADMIN",
    },
  });
  console.log("Admin user created:", admin.email);

  // Seed digital products
  const products = [
    {
      name: "AI Act Starter Toolkit",
      slug: "ai-act-starter-toolkit",
      description:
        "Essential templates and checklists for EU AI Act compliance. Includes risk classification worksheet, basic obligations checklist, AI policy template, compliance timeline tracker, and a basic DPIA template. Perfect for small teams getting started with AI governance.",
      shortDescription: "Essential templates and checklists for EU AI Act compliance",
      price: 4900,
      type: "ONE_TIME" as const,
      category: "AI_ACT_TOOLKIT" as const,
      features: [
        "Risk classification worksheet",
        "Basic obligations checklist",
        "AI policy template",
        "Compliance timeline tracker",
        "DPIA template (basic)",
      ],
      isActive: true,
      isFeatured: false,
    },
    {
      name: "AI Act Professional Toolkit",
      slug: "ai-act-pro-toolkit",
      description:
        "Comprehensive EU AI Act compliance package with legal-reviewed templates. Includes everything in the Starter Toolkit plus detailed FRIA template, technical documentation framework, quality management system template, post-market monitoring plan, conformity assessment guide, incident reporting procedures, human oversight protocols, and vendor AI governance clause templates.",
      shortDescription: "Comprehensive EU AI Act compliance package with legal-reviewed templates",
      price: 19900,
      compareAtPrice: 29900,
      type: "ONE_TIME" as const,
      category: "AI_ACT_TOOLKIT" as const,
      features: [
        "Everything in Starter, plus:",
        "Detailed FRIA template",
        "Technical documentation framework",
        "Quality management system template",
        "Post-market monitoring plan",
        "Conformity assessment guide",
        "Incident reporting procedures",
        "Human oversight protocols",
        "Vendor AI governance clause templates",
      ],
      isActive: true,
      isFeatured: true,
    },
    {
      name: "Security Questionnaire Basic Pack",
      slug: "questionnaire-basic-pack",
      description:
        "SOC 2 and ISO 27001 mapped questionnaire templates with 500+ pre-written answers specifically for AI systems. Includes vendor assessment template and editable formats.",
      shortDescription: "SOC 2 & ISO 27001 mapped questionnaires with 500+ pre-written answers",
      price: 9900,
      type: "ONE_TIME" as const,
      category: "SECURITY_QUESTIONNAIRE" as const,
      features: [
        "500+ pre-written answers",
        "SOC 2 Trust Criteria mapping",
        "ISO 27001 Annex A mapping",
        "AI-specific security controls",
        "Vendor assessment template",
        "Editable Word/Excel formats",
      ],
      isActive: true,
      isFeatured: false,
    },
    {
      name: "Security Questionnaire Enterprise Pack",
      slug: "questionnaire-enterprise-pack",
      description:
        "Complete security questionnaire automation with HIPAA, PCI DSS, NIST AI RMF, NIST CSF 2.0, and custom framework support. Includes 1000+ pre-written answers, evidence artifact templates, model card templates, and data flow diagrams.",
      shortDescription: "Complete security questionnaire automation for all major frameworks",
      price: 49900,
      compareAtPrice: 69900,
      type: "ONE_TIME" as const,
      category: "SECURITY_QUESTIONNAIRE" as const,
      features: [
        "Everything in Basic Pack, plus:",
        "1000+ pre-written answers",
        "HIPAA mapping",
        "PCI DSS mapping",
        "NIST AI RMF mapping",
        "NIST CSF 2.0 mapping",
        "Custom questionnaire builder",
        "Evidence artifact templates",
        "Model card templates",
        "Data flow diagrams",
      ],
      isActive: true,
      isFeatured: true,
    },
  ];

  for (const product of products) {
    await db.digitalProduct.upsert({
      where: { slug: product.slug },
      update: product,
      create: product,
    });
  }
  console.log(`${products.length} products seeded`);

  // Seed vendors
  const vendors = [
    {
      name: "OneTrust",
      slug: "onetrust",
      description:
        "OneTrust is a comprehensive trust intelligence platform that helps organizations manage privacy, security, data governance, GRC, third-party risk, ethics & compliance, and ESG programs. Their AI Governance module helps organizations inventory AI systems, assess risks, and manage compliance with emerging AI regulations including the EU AI Act.",
      shortDescription: "Comprehensive trust intelligence platform with AI governance capabilities",
      websiteUrl: "https://www.onetrust.com",
      category: "AI_GOVERNANCE_PLATFORM" as const,
      pricingModel: "ENTERPRISE_ONLY" as const,
      pricingStartsAt: "Contact Sales",
      hasFreeTrialOrTier: false,
      frameworksSupported: ["EU_AI_ACT", "SOC2", "ISO27001", "NIST_AI_RMF", "GDPR", "HIPAA", "PCI_DSS"],
      deploymentsSupported: ["cloud"],
      integrationsSupported: ["Jira", "ServiceNow", "Slack", "Salesforce"],
      hasDPA: true,
      gdprCompliant: true,
      soc2Certified: true,
      iso27001Certified: true,
      overallScore: 8.5,
      easeOfUse: 7.5,
      featureRichness: 9.5,
      valueForMoney: 6.5,
      customerSupport: 8.0,
      prosConsList: {
        pros: [
          "Most comprehensive feature set in the market",
          "Strong EU AI Act specific capabilities",
          "Extensive integration ecosystem",
          "Excellent regulatory intelligence",
        ],
        cons: [
          "Complex setup and implementation",
          "Expensive for smaller organizations",
          "Steep learning curve",
          "Can be overwhelming for simple use cases",
        ],
      },
      companySize: "enterprise",
      foundedYear: 2016,
      headquarters: "Atlanta, GA, USA",
      employeeCount: "2000+",
      isPublished: true,
      isFeatured: true,
    },
    {
      name: "Credo AI",
      slug: "credo-ai",
      description:
        "Credo AI is an AI governance platform purpose-built for responsible AI. It provides AI risk assessment, policy management, compliance tracking, and oversight tools specifically designed for the EU AI Act and other AI-specific regulations. Credo AI helps organizations implement responsible AI practices at scale.",
      shortDescription: "Purpose-built AI governance platform for responsible AI at scale",
      websiteUrl: "https://www.credo.ai",
      category: "AI_GOVERNANCE_PLATFORM" as const,
      pricingModel: "CONTACT_SALES" as const,
      pricingStartsAt: "Contact Sales",
      hasFreeTrialOrTier: true,
      frameworksSupported: ["EU_AI_ACT", "NIST_AI_RMF", "ISO42001"],
      deploymentsSupported: ["cloud"],
      integrationsSupported: ["MLflow", "GitHub", "Jira"],
      hasDPA: true,
      gdprCompliant: true,
      soc2Certified: true,
      iso27001Certified: false,
      overallScore: 8.8,
      easeOfUse: 8.5,
      featureRichness: 9.0,
      valueForMoney: 7.5,
      customerSupport: 8.5,
      prosConsList: {
        pros: [
          "Purpose-built for AI governance (not retrofitted)",
          "Strong EU AI Act compliance features",
          "Good MLOps integrations",
          "Clean, intuitive interface",
        ],
        cons: [
          "Relatively new company",
          "Smaller ecosystem than enterprise GRC tools",
          "Pricing not transparent",
        ],
      },
      companySize: "mid-market",
      foundedYear: 2020,
      headquarters: "San Francisco, CA, USA",
      employeeCount: "50-200",
      isPublished: true,
      isFeatured: true,
    },
    {
      name: "Vanta",
      slug: "vanta",
      description:
        "Vanta automates SOC 2, ISO 27001, HIPAA, PCI DSS, and GDPR compliance. While not specifically AI-focused, Vanta's continuous monitoring and automated evidence collection is highly relevant for AI companies needing to demonstrate security and compliance posture to customers and regulators.",
      shortDescription: "Automated compliance for SOC 2, ISO 27001, HIPAA, and more",
      websiteUrl: "https://www.vanta.com",
      category: "GRC_PLATFORM" as const,
      pricingModel: "SUBSCRIPTION" as const,
      pricingStartsAt: "$4,000/year",
      hasFreeTrialOrTier: true,
      frameworksSupported: ["SOC2", "ISO27001", "HIPAA", "PCI_DSS", "GDPR"],
      deploymentsSupported: ["cloud"],
      integrationsSupported: ["AWS", "GCP", "Azure", "GitHub", "Jira", "Slack"],
      hasDPA: true,
      gdprCompliant: true,
      soc2Certified: true,
      iso27001Certified: true,
      overallScore: 8.7,
      easeOfUse: 9.0,
      featureRichness: 8.5,
      valueForMoney: 8.0,
      customerSupport: 8.5,
      prosConsList: {
        pros: [
          "Excellent automation and ease of use",
          "Fast time to compliance",
          "Great integrations with cloud providers",
          "Transparent pricing",
        ],
        cons: [
          "Not AI-specific governance",
          "Limited EU AI Act support",
          "Can be expensive for startups",
        ],
      },
      companySize: "startup",
      foundedYear: 2018,
      headquarters: "San Francisco, CA, USA",
      employeeCount: "500-1000",
      isPublished: true,
      isFeatured: true,
    },
    {
      name: "Holistic AI",
      slug: "holistic-ai",
      description:
        "Holistic AI provides an end-to-end AI governance, risk, and compliance platform. Their tools cover AI auditing, bias detection, risk management, and regulatory compliance including the EU AI Act. They also offer consulting services for complex compliance projects.",
      shortDescription: "End-to-end AI governance, risk, and compliance platform",
      websiteUrl: "https://www.holisticai.com",
      category: "AI_GOVERNANCE_PLATFORM" as const,
      pricingModel: "CONTACT_SALES" as const,
      pricingStartsAt: "Contact Sales",
      hasFreeTrialOrTier: true,
      frameworksSupported: ["EU_AI_ACT", "NIST_AI_RMF", "ISO42001", "NYC_LL144"],
      deploymentsSupported: ["cloud", "on-prem"],
      integrationsSupported: ["Python SDK", "REST API"],
      hasDPA: true,
      gdprCompliant: true,
      soc2Certified: true,
      iso27001Certified: true,
      overallScore: 8.3,
      easeOfUse: 7.5,
      featureRichness: 8.5,
      valueForMoney: 7.5,
      customerSupport: 8.0,
      prosConsList: {
        pros: [
          "Strong AI-specific audit capabilities",
          "Excellent bias detection tools",
          "Academic research backing",
          "Flexible deployment options",
        ],
        cons: [
          "Pricing not transparent",
          "UI could be more polished",
          "Fewer integrations than competitors",
        ],
      },
      companySize: "mid-market",
      foundedYear: 2018,
      headquarters: "London, UK",
      employeeCount: "50-200",
      isPublished: true,
      isFeatured: false,
    },
    {
      name: "IBM OpenPages",
      slug: "ibm-openpages",
      description:
        "IBM OpenPages is an enterprise GRC platform with AI-powered risk management capabilities. Part of IBM's broader AI governance strategy, OpenPages offers model risk management, regulatory compliance tracking, and AI lifecycle governance for large enterprises.",
      shortDescription: "Enterprise GRC platform with AI-powered risk management",
      websiteUrl: "https://www.ibm.com/products/openpages",
      category: "GRC_PLATFORM" as const,
      pricingModel: "ENTERPRISE_ONLY" as const,
      pricingStartsAt: "Contact Sales",
      hasFreeTrialOrTier: true,
      frameworksSupported: ["SOC2", "ISO27001", "NIST_AI_RMF", "Basel", "EU_AI_ACT"],
      deploymentsSupported: ["cloud", "on-prem", "hybrid"],
      integrationsSupported: ["IBM Cloud", "Watson", "ServiceNow"],
      hasDPA: true,
      gdprCompliant: true,
      soc2Certified: true,
      iso27001Certified: true,
      overallScore: 7.8,
      easeOfUse: 6.5,
      featureRichness: 9.0,
      valueForMoney: 6.0,
      customerSupport: 7.5,
      prosConsList: {
        pros: [
          "Enterprise-grade scalability",
          "Deep IBM ecosystem integration",
          "Comprehensive model risk management",
          "Strong in regulated industries (banking, insurance)",
        ],
        cons: [
          "Complex and expensive",
          "IBM ecosystem dependency",
          "Steep learning curve",
          "Overkill for smaller organizations",
        ],
      },
      companySize: "enterprise",
      foundedYear: 2004,
      headquarters: "Armonk, NY, USA",
      employeeCount: "10000+",
      isPublished: true,
      isFeatured: false,
    },
    // ==========================================
    // NEW VENDORS - Wave 2
    // ==========================================
    {
      name: "SAP AI Governance",
      slug: "sap-ai-governance",
      description:
        "SAP AI Governance is part of SAP's broader Business AI platform, providing enterprise-grade AI lifecycle governance deeply integrated with SAP's ERP and business process ecosystem. With ISO/IEC 42001 certification and a dedicated EU AI Cloud, SAP offers European enterprises a sovereign AI stack with built-in compliance for the EU AI Act, GDPR, and NIST AI RMF. The platform embeds governance into SAP AI Core, AI Launchpad, and the LeanIX AI Agent Hub for centralized AI system inventory and risk management.",
      shortDescription: "Enterprise AI governance deeply integrated with SAP's business process ecosystem and EU-sovereign cloud",
      websiteUrl: "https://www.sap.com/products/artificial-intelligence/ai-ethics.html",
      category: "AI_GOVERNANCE_PLATFORM" as const,
      pricingModel: "ENTERPRISE_ONLY" as const,
      pricingStartsAt: "Contact Sales",
      hasFreeTrialOrTier: false,
      frameworksSupported: ["EU_AI_ACT", "GDPR", "ISO42001", "NIST_AI_RMF", "ISO27001", "SOC2"],
      deploymentsSupported: ["cloud", "on-prem", "hybrid"],
      integrationsSupported: ["SAP S/4HANA", "SAP BTP", "SAP AI Core", "SAP LeanIX", "SAP SuccessFactors", "Microsoft Azure", "AWS", "GCP"],
      hasDPA: true,
      gdprCompliant: true,
      soc2Certified: true,
      iso27001Certified: true,
      overallScore: 8.1,
      easeOfUse: 6.0,
      featureRichness: 9.0,
      valueForMoney: 5.5,
      customerSupport: 7.5,
      prosConsList: {
        pros: [
          "ISO/IEC 42001 certified AI management system",
          "Dedicated EU AI Cloud for data sovereignty",
          "Deep integration with SAP ERP and business processes",
          "Strong alignment with EU AI Act requirements",
          "Enterprise-scale governance for large multinationals",
        ],
        cons: [
          "Heavily tied to SAP ecosystem — limited value outside it",
          "Very expensive and complex to implement",
          "Steep learning curve for non-SAP shops",
          "AI governance features still maturing compared to pure-play vendors",
        ],
      },
      companySize: "enterprise",
      foundedYear: 1972,
      headquarters: "Walldorf, Germany",
      employeeCount: "100000+",
      isPublished: true,
      isFeatured: true,
    },
    {
      name: "ServiceNow GRC",
      slug: "servicenow-grc",
      description:
        "ServiceNow Governance, Risk, and Compliance (GRC) is a comprehensive enterprise GRC platform built on the Now Platform. It unifies policy management, risk assessment, compliance tracking, audit management, and vendor risk management into a single workflow-driven system with AI-powered remediation recommendations. While not AI-governance-specific, its extensibility and enterprise adoption make it a strong foundation for organizations building AI compliance programs alongside broader IT GRC.",
      shortDescription: "Enterprise GRC platform with AI-powered risk management built on the Now Platform",
      websiteUrl: "https://www.servicenow.com/products/governance-risk-and-compliance.html",
      category: "GRC_PLATFORM" as const,
      pricingModel: "PER_SEAT" as const,
      pricingStartsAt: "$50,000/year",
      hasFreeTrialOrTier: false,
      frameworksSupported: ["SOC2", "ISO27001", "NIST_AI_RMF", "GDPR", "HIPAA", "PCI_DSS", "EU_AI_ACT"],
      deploymentsSupported: ["cloud"],
      integrationsSupported: ["ServiceNow ITSM", "ServiceNow ITOM", "Jira", "Slack", "Microsoft Teams", "Splunk", "Qualys", "Tenable", "AWS", "Azure", "GCP"],
      hasDPA: true,
      gdprCompliant: true,
      soc2Certified: true,
      iso27001Certified: true,
      overallScore: 8.0,
      easeOfUse: 6.5,
      featureRichness: 9.2,
      valueForMoney: 5.5,
      customerSupport: 7.5,
      prosConsList: {
        pros: [
          "Extremely powerful workflow automation and orchestration",
          "Unified platform spanning IT, security, and GRC",
          "Massive enterprise ecosystem and marketplace",
          "AI-powered remediation and risk prioritization",
          "Strong audit management capabilities",
        ],
        cons: [
          "Very expensive — contracts range $50K-$500K/year",
          "Not purpose-built for AI governance specifically",
          "Requires significant configuration and admin expertise",
          "Cloud-only deployment may not suit data sovereignty needs",
          "Steep learning curve for new administrators",
        ],
      },
      companySize: "enterprise",
      foundedYear: 2003,
      headquarters: "Santa Clara, CA, USA",
      employeeCount: "25000+",
      isPublished: true,
      isFeatured: false,
    },
    {
      name: "Securiti AI",
      slug: "securiti-ai",
      description:
        "Securiti AI provides a unified Data Command Center that combines AI security and governance, data security posture management (DSPM), privacy automation, and data governance into a single platform. Its AI Governance Center enables discovery and cataloging of AI models across public clouds, private clouds, and SaaS applications, with risk classification aligned to global regulatory requirements including the EU AI Act. Acquired by Veeam in late 2025, Securiti offers 1000+ pre-built connectors for comprehensive data and AI visibility.",
      shortDescription: "Unified data command center combining AI governance, DSPM, and privacy automation",
      websiteUrl: "https://securiti.ai",
      category: "DATA_GOVERNANCE" as const,
      pricingModel: "CONTACT_SALES" as const,
      pricingStartsAt: "Contact Sales",
      hasFreeTrialOrTier: true,
      frameworksSupported: ["EU_AI_ACT", "GDPR", "HIPAA", "SOC2", "ISO27001", "NIST_AI_RMF", "PCI_DSS"],
      deploymentsSupported: ["cloud", "hybrid"],
      integrationsSupported: ["AWS", "Azure", "GCP", "Snowflake", "Databricks", "Salesforce", "ServiceNow", "Workday", "Slack", "OneDrive", "SharePoint"],
      hasDPA: true,
      gdprCompliant: true,
      soc2Certified: true,
      iso27001Certified: true,
      overallScore: 8.4,
      easeOfUse: 7.5,
      featureRichness: 9.0,
      valueForMoney: 7.0,
      customerSupport: 7.5,
      prosConsList: {
        pros: [
          "1000+ pre-built data connectors for comprehensive visibility",
          "Strong combination of AI governance + data security + privacy",
          "Automated AI model discovery and risk classification",
          "Maps AI models to data sources and compliance obligations",
          "Backed by Veeam acquisition for long-term stability",
        ],
        cons: [
          "Pricing not transparent — requires custom quote",
          "Data-centric approach may lack depth in model-level governance",
          "Integration complexity with large enterprises",
          "Post-acquisition roadmap uncertainty",
        ],
      },
      companySize: "mid-market",
      foundedYear: 2018,
      headquarters: "San Jose, CA, USA",
      employeeCount: "500-1000",
      isPublished: true,
      isFeatured: false,
    },
    {
      name: "BigID",
      slug: "bigid",
      description:
        "BigID is an enterprise data security and intelligence platform that combines AI governance, DSPM, data privacy, and data governance into a unified solution trusted by Fortune 500 companies. The platform offers AI TRiSM (Trust, Risk, and Security Management) and AI SPM (AI Security Posture Management) with agentic AI features to automate governance and protection of AI data and models. BigID Next, their cloud-native platform, adds Vendor AI Assessment for evaluating third-party AI risks alongside their core data discovery and classification engine.",
      shortDescription: "Enterprise data intelligence platform with AI governance, DSPM, and automated data discovery",
      websiteUrl: "https://bigid.com",
      category: "DATA_GOVERNANCE" as const,
      pricingModel: "CONTACT_SALES" as const,
      pricingStartsAt: "Contact Sales",
      hasFreeTrialOrTier: true,
      frameworksSupported: ["EU_AI_ACT", "GDPR", "HIPAA", "SOC2", "ISO27001", "NIST_AI_RMF", "PCI_DSS"],
      deploymentsSupported: ["cloud", "on-prem", "hybrid"],
      integrationsSupported: ["Snowflake", "Databricks", "AWS", "Azure", "GCP", "ServiceNow", "Wiz", "Tanium", "Alation", "Collibra", "Salesforce", "Oracle"],
      hasDPA: true,
      gdprCompliant: true,
      soc2Certified: true,
      iso27001Certified: true,
      overallScore: 8.5,
      easeOfUse: 7.0,
      featureRichness: 9.2,
      valueForMoney: 6.5,
      customerSupport: 7.5,
      prosConsList: {
        pros: [
          "Industry-leading data discovery and classification engine",
          "Strong AI TRiSM and vendor AI assessment capabilities",
          "Comprehensive coverage across structured and unstructured data",
          "Named Leader in IDC MarketScape for Data Privacy Compliance",
          "Flexible deployment options including on-prem and hybrid",
        ],
        cons: [
          "Pricing not transparent and can be expensive",
          "Data-first approach — less depth on model monitoring and MLOps",
          "Can be complex to configure for smaller organizations",
          "Some features require additional modules at extra cost",
        ],
      },
      companySize: "mid-market",
      foundedYear: 2016,
      headquarters: "New York, NY, USA",
      employeeCount: "200-500",
      isPublished: true,
      isFeatured: false,
    },
    {
      name: "TrustArc",
      slug: "trustarc",
      description:
        "TrustArc is a veteran privacy management platform with over 28 years of global privacy expertise. Their flagship Arc platform, launched in late 2025, brings AI-powered privacy management with Arc Intelligence — a context-aware AI layer backed by Nymity Research, a repository of 50,000+ expert-written privacy references updated daily. TrustArc excels at privacy compliance automation, consent management, and data governance, with growing capabilities in AI governance and EU AI Act readiness.",
      shortDescription: "AI-powered privacy management platform with 28+ years of global privacy expertise",
      websiteUrl: "https://trustarc.com",
      category: "PRIVACY_COMPLIANCE" as const,
      pricingModel: "SUBSCRIPTION" as const,
      pricingStartsAt: "$15,000/year",
      hasFreeTrialOrTier: false,
      frameworksSupported: ["GDPR", "EU_AI_ACT", "HIPAA", "SOC2", "ISO27001", "PCI_DSS", "NIST_AI_RMF"],
      deploymentsSupported: ["cloud"],
      integrationsSupported: ["OneTrust", "Salesforce", "SAP", "Google Analytics", "Adobe", "HubSpot", "WordPress", "Shopify"],
      hasDPA: true,
      gdprCompliant: true,
      soc2Certified: true,
      iso27001Certified: true,
      overallScore: 7.9,
      easeOfUse: 7.5,
      featureRichness: 8.0,
      valueForMoney: 7.0,
      customerSupport: 8.0,
      prosConsList: {
        pros: [
          "28+ years of privacy expertise — deep regulatory knowledge",
          "Arc Intelligence powered by 50,000+ Nymity Research references",
          "Strong consent management and cookie compliance",
          "Trusted by major enterprises globally",
          "Good balance of automation and expert advisory services",
        ],
        cons: [
          "Privacy-first platform — AI governance is an evolving capability",
          "Cloud-only deployment limits some regulated industries",
          "Interface can feel dated compared to newer competitors",
          "Less technical depth for MLOps and model monitoring",
        ],
      },
      companySize: "mid-market",
      foundedYear: 1997,
      headquarters: "San Francisco, CA, USA",
      employeeCount: "200-500",
      isPublished: true,
      isFeatured: false,
    },
    {
      name: "Dataiku",
      slug: "dataiku",
      description:
        "Dataiku is the Universal AI Platform that combines data preparation, machine learning, MLOps, and AI governance in a single collaborative environment. Named a Leader in the IDC MarketScape for Unified AI Governance 2025-2026, Dataiku embeds governance directly into the AI development workflow with built-in enforcement mechanisms that prevent noncompliant AI systems from reaching production. The platform supports DataOps, MLOps, and LLMOps under one roof with enterprise-grade RBAC, audit logs, and explainable AI.",
      shortDescription: "Universal AI platform combining MLOps, data science, and embedded AI governance in one environment",
      websiteUrl: "https://www.dataiku.com",
      category: "MLOPS_WITH_GOVERNANCE" as const,
      pricingModel: "ENTERPRISE_ONLY" as const,
      pricingStartsAt: "$48,000/year",
      hasFreeTrialOrTier: true,
      frameworksSupported: ["EU_AI_ACT", "GDPR", "SOC2", "ISO27001", "NIST_AI_RMF", "ISO42001"],
      deploymentsSupported: ["cloud", "on-prem", "hybrid"],
      integrationsSupported: ["Snowflake", "Databricks", "AWS SageMaker", "Azure ML", "GCP Vertex AI", "Tableau", "Power BI", "Spark", "Kubernetes", "GitHub", "MLflow"],
      hasDPA: true,
      gdprCompliant: true,
      soc2Certified: true,
      iso27001Certified: true,
      overallScore: 8.6,
      easeOfUse: 8.0,
      featureRichness: 9.3,
      valueForMoney: 7.0,
      customerSupport: 8.0,
      prosConsList: {
        pros: [
          "Named Leader in IDC MarketScape for Unified AI Governance",
          "Governance embedded directly into the ML development workflow",
          "Supports DataOps, MLOps, and LLMOps in a single platform",
          "Excellent collaboration features for cross-functional teams",
          "Flexible deployment including on-prem and air-gapped options",
        ],
        cons: [
          "Pricing starts high — $4,000+/month minimum",
          "Can be overkill if you only need governance (not full MLOps)",
          "Requires investment in training and onboarding",
          "Governance features are integrated, not standalone — harder to adopt piecemeal",
        ],
      },
      companySize: "enterprise",
      foundedYear: 2013,
      headquarters: "New York, NY, USA",
      employeeCount: "1000-2000",
      isPublished: true,
      isFeatured: true,
    },
    {
      name: "Arthur AI",
      slug: "arthur-ai",
      description:
        "Arthur AI is an AI performance monitoring and governance platform designed for both traditional ML and generative AI models, with expanding support for agentic AI systems. The platform provides real-time model evaluation, drift detection, fairness checks, and explainability through a federated architecture that keeps data within your environment. Arthur open-sourced the Arthur Engine in 2025 — the first real-time AI evaluation engine — and offers an intuitive AI control plane for full visibility over AI deployments.",
      shortDescription: "AI monitoring and governance platform with real-time evaluation for ML, LLMs, and AI agents",
      websiteUrl: "https://www.arthur.ai",
      category: "MODEL_RISK_MANAGEMENT" as const,
      pricingModel: "FREEMIUM" as const,
      pricingStartsAt: "$0 (Free tier) / $60/month (Premium)",
      hasFreeTrialOrTier: true,
      frameworksSupported: ["EU_AI_ACT", "NIST_AI_RMF", "SOC2", "ISO42001"],
      deploymentsSupported: ["cloud", "on-prem", "hybrid"],
      integrationsSupported: ["AWS SageMaker", "GCP Vertex AI", "Azure ML", "MLflow", "Databricks", "Hugging Face", "Python SDK", "REST API"],
      hasDPA: true,
      gdprCompliant: true,
      soc2Certified: true,
      iso27001Certified: false,
      overallScore: 8.2,
      easeOfUse: 8.0,
      featureRichness: 8.5,
      valueForMoney: 8.5,
      customerSupport: 7.5,
      prosConsList: {
        pros: [
          "Free tier available — accessible entry point",
          "Open-source Arthur Engine for real-time AI evaluation",
          "Strong support for generative AI and agentic systems",
          "Federated architecture keeps data in your environment",
          "Model-agnostic — works with any ML/LLM framework",
        ],
        cons: [
          "Smaller company with limited enterprise track record",
          "Governance features less comprehensive than full GRC platforms",
          "Limited regulatory framework coverage beyond AI-specific standards",
          "Fewer integrations than larger competitors",
        ],
      },
      companySize: "startup",
      foundedYear: 2018,
      headquarters: "New York, NY, USA",
      employeeCount: "50-100",
      isPublished: true,
      isFeatured: false,
    },
    {
      name: "Fiddler AI",
      slug: "fiddler-ai",
      description:
        "Fiddler AI is the pioneer in AI Observability and Security, offering an enterprise-grade platform for monitoring, explaining, and securing AI agents, LLM applications, and ML models in production. The platform provides 100+ out-of-the-box metrics covering hallucination detection, toxicity scoring, PII/PHI protection, drift monitoring, and custom business KPIs. Recognized as a Leader in AI Agent Security & Risk Management by CB Insights and featured in the IDC ProductScape for Generative AI Governance Platforms 2025, Fiddler serves Fortune 500 organizations across multiple deployment modes.",
      shortDescription: "AI observability and security platform for monitoring LLMs, ML models, and AI agents in production",
      websiteUrl: "https://www.fiddler.ai",
      category: "MODEL_RISK_MANAGEMENT" as const,
      pricingModel: "USAGE_BASED" as const,
      pricingStartsAt: "Contact Sales (token-based pricing)",
      hasFreeTrialOrTier: true,
      frameworksSupported: ["EU_AI_ACT", "NIST_AI_RMF", "SOC2", "ISO27001"],
      deploymentsSupported: ["cloud", "on-prem", "hybrid"],
      integrationsSupported: ["AWS SageMaker", "Azure ML", "GCP Vertex AI", "Datadog", "MLflow", "Databricks", "Kubernetes", "Python SDK", "REST API"],
      hasDPA: true,
      gdprCompliant: true,
      soc2Certified: true,
      iso27001Certified: false,
      overallScore: 8.3,
      easeOfUse: 7.5,
      featureRichness: 8.8,
      valueForMoney: 7.5,
      customerSupport: 8.0,
      prosConsList: {
        pros: [
          "100+ out-of-the-box metrics for LLM and ML monitoring",
          "Strong hallucination detection and toxicity scoring",
          "Flexible deployment including air-gapped and on-prem",
          "Named Leader in AI Agent Security by CB Insights",
          "Purpose-built Fiddler Trust Models for high-accuracy scoring",
        ],
        cons: [
          "Token-based pricing can be hard to predict at scale",
          "Primarily focused on observability — less on policy/GRC",
          "Smaller company compared to platform players",
          "Limited coverage of non-AI compliance frameworks",
        ],
      },
      companySize: "startup",
      foundedYear: 2018,
      headquarters: "Palo Alto, CA, USA",
      employeeCount: "50-150",
      isPublished: true,
      isFeatured: false,
    },
    {
      name: "Weights & Biases",
      slug: "weights-and-biases",
      description:
        "Weights & Biases (W&B) is the leading AI developer platform for experiment tracking, model versioning, dataset management, and ML pipeline orchestration. While primarily an MLOps tool, W&B provides governance-relevant capabilities through its Registry (model and dataset versioning with access controls), RBAC with SCIM support, comprehensive audit trails, and reproducibility tracking. Acquired by CoreWeave in 2025, W&B serves as a foundational layer for ML governance by ensuring traceability and accountability across the AI development lifecycle.",
      shortDescription: "AI developer platform with experiment tracking, model registry, and ML governance capabilities",
      websiteUrl: "https://wandb.ai",
      category: "MLOPS_WITH_GOVERNANCE" as const,
      pricingModel: "FREEMIUM" as const,
      pricingStartsAt: "$0 (Free tier) / $50/user/month (Pro)",
      hasFreeTrialOrTier: true,
      frameworksSupported: ["NIST_AI_RMF", "ISO42001"],
      deploymentsSupported: ["cloud", "on-prem", "hybrid"],
      integrationsSupported: ["PyTorch", "TensorFlow", "Hugging Face", "Keras", "Scikit-learn", "XGBoost", "LangChain", "LlamaIndex", "AWS SageMaker", "Azure ML", "GCP Vertex AI", "Databricks", "Kubernetes"],
      hasDPA: true,
      gdprCompliant: true,
      soc2Certified: true,
      iso27001Certified: false,
      overallScore: 8.4,
      easeOfUse: 9.0,
      featureRichness: 8.0,
      valueForMoney: 9.0,
      customerSupport: 7.5,
      prosConsList: {
        pros: [
          "Free tier with generous limits — best value for ML teams",
          "Best-in-class experiment tracking and reproducibility",
          "W&B Registry provides model versioning with access controls",
          "Massive community adoption (700K+ users)",
          "Excellent developer experience and documentation",
        ],
        cons: [
          "Not a governance platform — governance is a byproduct of MLOps features",
          "No direct EU AI Act or regulatory compliance modules",
          "Limited policy management and risk assessment capabilities",
          "Post-CoreWeave acquisition roadmap may shift priorities",
        ],
      },
      companySize: "mid-market",
      foundedYear: 2017,
      headquarters: "San Francisco, CA, USA",
      employeeCount: "200-500",
      isPublished: true,
      isFeatured: false,
    },
    {
      name: "Monitaur",
      slug: "monitaur",
      description:
        "Monitaur is a purpose-built AI governance platform designed specifically for regulated enterprises, with particular strength in the insurance and financial services industries. The platform follows a three-stage 'policy-to-proof' methodology that guides organizations from defining governance frameworks through actionable practices to scaled implementation. Recognized in the 2025 Gartner Market Guide for AI TRiSM and by MarketsandMarkets as a leader among end-to-end governance platforms, Monitaur supports everything from policy creation and model inventory to continuous validation of model performance, bias, and drift across both classical ML and generative AI.",
      shortDescription: "Purpose-built AI governance platform for regulated enterprises with policy-to-proof methodology",
      websiteUrl: "https://www.monitaur.ai",
      category: "AI_GOVERNANCE_PLATFORM" as const,
      pricingModel: "CONTACT_SALES" as const,
      pricingStartsAt: "Contact Sales",
      hasFreeTrialOrTier: false,
      frameworksSupported: ["EU_AI_ACT", "NIST_AI_RMF", "SOC2", "ISO42001", "SR_11_7"],
      deploymentsSupported: ["cloud"],
      integrationsSupported: ["Python SDK", "REST API", "Jupyter Notebooks", "MLflow"],
      hasDPA: true,
      gdprCompliant: true,
      soc2Certified: true,
      iso27001Certified: false,
      overallScore: 7.8,
      easeOfUse: 7.5,
      featureRichness: 8.0,
      valueForMoney: 7.5,
      customerSupport: 8.5,
      prosConsList: {
        pros: [
          "Purpose-built for regulated industries (insurance, financial services)",
          "Named in Gartner Market Guide for AI TRiSM 2025",
          "Strong policy-to-proof methodology for governance maturity",
          "Vendor AI governance solution for third-party AI risk management",
          "Supports both classical ML and generative AI governance",
        ],
        cons: [
          "Very small company (~10 employees) — execution risk",
          "Limited integrations compared to larger platforms",
          "Cloud-only deployment may not suit all regulated industries",
          "Less brand recognition than enterprise GRC incumbents",
        ],
      },
      companySize: "startup",
      foundedYear: 2019,
      headquarters: "Duxbury, MA, USA",
      employeeCount: "10-50",
      isPublished: true,
      isFeatured: false,
    },
  ];

  for (const vendor of vendors) {
    await db.vendor.upsert({
      where: { slug: vendor.slug },
      update: vendor,
      create: vendor,
    });
  }
  console.log(`${vendors.length} vendors seeded`);

  // Seed email sequence
  const sequence = await db.emailSequence.upsert({
    where: { slug: "welcome-funnel" },
    update: {},
    create: {
      name: "Welcome Funnel",
      slug: "welcome-funnel",
      description: "5-email drip sequence for new subscribers",
      isActive: true,
    },
  });

  const steps = [
    {
      stepNumber: 1,
      subject: "Welcome to AIGovHub + Your Free Checklist",
      templateId: "welcome",
      delayHours: 0,
    },
    {
      stepNumber: 2,
      subject: "3 AI Compliance Mistakes That Cost Companies Millions",
      templateId: "drip-1-intro",
      delayHours: 48,
    },
    {
      stepNumber: 3,
      subject: "How [Company] Achieved EU AI Act Compliance in 6 Weeks",
      templateId: "drip-2-value",
      delayHours: 96,
    },
    {
      stepNumber: 4,
      subject: "Your AI Compliance Toolkit (Special Offer Inside)",
      templateId: "drip-3-case-study",
      delayHours: 168,
    },
    {
      stepNumber: 5,
      subject: "EU AI Act Deadline: Are You Ready? (Last Chance)",
      templateId: "drip-4-offer",
      delayHours: 240,
    },
  ];

  for (const step of steps) {
    await db.emailSequenceStep.upsert({
      where: {
        sequenceId_stepNumber: {
          sequenceId: sequence.id,
          stepNumber: step.stepNumber,
        },
      },
      update: step,
      create: { ...step, sequenceId: sequence.id },
    });
  }
  console.log("Email sequence seeded");

  // Seed agent sources (RSS feeds for autonomous content pipeline)
  const agentSources = [
    {
      name: "EU AI Act Official",
      url: "https://artificialintelligenceact.eu/feed/",
      type: "REGULATORY_BODY" as const,
      category: "regulation",
    },
    {
      name: "NIST AI",
      url: "https://www.nist.gov/artificial-intelligence/rss.xml",
      type: "REGULATORY_BODY" as const,
      category: "framework-update",
    },
    {
      name: "MIT Technology Review - AI",
      url: "https://www.technologyreview.com/topic/artificial-intelligence/feed",
      type: "RSS_FEED" as const,
      category: "research",
    },
    {
      name: "TechCrunch - AI",
      url: "https://techcrunch.com/category/artificial-intelligence/feed/",
      type: "RSS_FEED" as const,
      category: "vendor-news",
    },
    {
      name: "The Verge - AI",
      url: "https://www.theverge.com/rss/ai-artificial-intelligence/index.xml",
      type: "RSS_FEED" as const,
      category: "vendor-news",
    },
    {
      name: "OECD AI Policy Observatory",
      url: "https://oecd.ai/en/feed",
      type: "REGULATORY_BODY" as const,
      category: "regulation",
    },
    {
      name: "ICO UK Blog",
      url: "https://ico.org.uk/about-the-ico/media-centre/news-and-blogs/rss/",
      type: "REGULATORY_BODY" as const,
      category: "regulation",
    },
    {
      name: "OneTrust Blog",
      url: "https://www.onetrust.com/blog/feed/",
      type: "RSS_FEED" as const,
      category: "vendor-news",
    },
    {
      name: "IAPP - Privacy",
      url: "https://iapp.org/rss/",
      type: "INDUSTRY_REPORT" as const,
      category: "best-practice",
    },
    {
      name: "Brookings - AI",
      url: "https://www.brookings.edu/topic/artificial-intelligence/feed/",
      type: "RESEARCH_PAPER" as const,
      category: "research",
    },
    {
      name: "Stanford HAI",
      url: "https://hai.stanford.edu/news/rss.xml",
      type: "RESEARCH_PAPER" as const,
      category: "research",
    },
    {
      name: "VentureBeat - AI",
      url: "https://venturebeat.com/category/ai/feed/",
      type: "RSS_FEED" as const,
      category: "vendor-news",
    },
    {
      name: "European Commission Digital",
      url: "https://digital-strategy.ec.europa.eu/en/rss.xml",
      type: "REGULATORY_BODY" as const,
      category: "regulation",
    },
    {
      name: "Responsible AI Institute",
      url: "https://www.responsible.ai/feed/",
      type: "INDUSTRY_REPORT" as const,
      category: "best-practice",
    },
    {
      name: "Wired - AI",
      url: "https://www.wired.com/feed/tag/ai/latest/rss",
      type: "RSS_FEED" as const,
      category: "vendor-news",
    },
  ];

  for (const source of agentSources) {
    await db.agentSource.upsert({
      where: {
        id: `seed-${source.name.toLowerCase().replace(/[^a-z0-9]/g, "-")}`,
      },
      update: { ...source },
      create: {
        id: `seed-${source.name.toLowerCase().replace(/[^a-z0-9]/g, "-")}`,
        ...source,
      },
    });
  }
  console.log(`${agentSources.length} agent sources seeded`);

  // Seed default agent settings
  const defaultSettings = [
    { key: "enabled", value: true, description: "Master switch for the agent pipeline" },
    { key: "dailyArticleTarget", value: 2, description: "Number of articles to produce per pipeline run" },
    { key: "maxRewriteAttempts", value: 2, description: "Maximum rewrites before rejection" },
    { key: "minQAScore", value: 7.0, description: "Minimum QA score for approval (1-10)" },
    { key: "budgetLimitUsd", value: 5.0, description: "Maximum cost per pipeline run in USD" },
  ];

  for (const setting of defaultSettings) {
    await db.agentSettings.upsert({
      where: { key: setting.key },
      update: {},
      create: {
        key: setting.key,
        value: setting.value as never,
        description: setting.description,
      },
    });
  }
  console.log("Agent settings seeded");

  console.log("Seeding complete!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await db.$disconnect();
  });
