/**
 * Seed script: Add ~65 real vendors across all compliance domains.
 *
 * Usage:
 *   npx tsx scripts/seed-multi-domain-vendors.ts
 *
 * This script is idempotent — it skips vendors whose slug already exists.
 */

import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const vendors = [
  // ============================================
  // E-INVOICING & TAX COMPLIANCE (12 vendors)
  // ============================================
  {
    name: "Avalara",
    slug: "avalara",
    description: "Avalara is a leading provider of cloud-based tax compliance automation for businesses of all sizes. The platform automates the calculation, collection, filing, and remittance of transactional taxes including sales tax, VAT, GST, and excise tax across more than 190 countries. Acquired by Vista Equity Partners in 2022 for $8.4 billion, Avalara integrates with over 1,200 ERP, ecommerce, and billing systems.",
    shortDescription: "Cloud-based tax compliance automation platform covering sales tax, VAT, and GST across 190+ countries.",
    websiteUrl: "https://www.avalara.com",
    category: "TAX_COMPLIANCE",
    subcategories: ["Sales Tax", "VAT Compliance", "Tax Filing", "E-Invoicing"],
    pricingModel: "SUBSCRIPTION",
    hasFreeTrialOrTier: true,
    frameworksSupported: ["SOX", "GAAP", "IFRS", "EU VAT Directive", "Peppol"],
    deploymentsSupported: ["Cloud"],
    integrationsSupported: ["Shopify", "Magento", "NetSuite", "SAP", "Salesforce", "QuickBooks", "Stripe", "BigCommerce"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: true,
    overallScore: 8.6,
    easeOfUse: 8.0,
    featureRichness: 9.0,
    valueForMoney: 7.5,
    customerSupport: 8.0,
    keyFeatures: ["Automated tax calculation", "Real-time tax rate lookup", "Sales tax filing & remittance", "VAT/GST compliance", "Exemption certificate management", "1,200+ integrations", "Cross-border tax compliance"],
    companySize: "Enterprise",
    foundedYear: 2004,
    headquarters: "Durham, NC",
    employeeCount: "5,001-10,000",
    isPublished: true,
    isFeatured: true,
  },
  {
    name: "Vertex",
    slug: "vertex-tax",
    description: "Vertex Inc. is a publicly traded tax technology company specializing in tax determination, compliance, and reporting solutions for corporations worldwide. Vertex serves over 4,000 customers including more than half of the Fortune 500, automating indirect tax processes across sales, use, value-added, payroll, and communications taxes. The platform supports tax calculations in over 195 countries.",
    shortDescription: "Enterprise tax technology platform automating indirect tax compliance for half the Fortune 500.",
    websiteUrl: "https://www.vertexinc.com",
    category: "TAX_COMPLIANCE",
    subcategories: ["Indirect Tax", "Tax Determination", "Tax Reporting", "E-Invoicing"],
    pricingModel: "ENTERPRISE_ONLY",
    hasFreeTrialOrTier: false,
    frameworksSupported: ["SOX", "GAAP", "IFRS", "EU VAT Directive", "Peppol", "OECD BEPS"],
    deploymentsSupported: ["Cloud", "On-Premise", "Hybrid"],
    integrationsSupported: ["SAP", "Oracle", "Microsoft Dynamics", "Salesforce", "Workday", "Coupa"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: true,
    overallScore: 8.8,
    easeOfUse: 7.5,
    featureRichness: 9.5,
    valueForMoney: 7.0,
    customerSupport: 8.5,
    keyFeatures: ["Tax determination engine", "Tax data management", "Compliance reporting", "E-invoicing support", "Tax analytics & visualization", "195+ country coverage", "ERP-native integrations"],
    companySize: "Enterprise",
    foundedYear: 1978,
    headquarters: "King of Prussia, PA",
    employeeCount: "1,001-5,000",
    isPublished: true,
    isFeatured: true,
  },
  {
    name: "Sovos",
    slug: "sovos",
    description: "Sovos is a global tax compliance and e-invoicing platform that helps businesses navigate complex regulatory mandates. Sovos handles over 11 billion transactions annually and supports tax determination, e-invoicing, tax reporting, and regulatory analysis across more than 70 countries. The company has grown significantly through acquisitions including Convey Compliance, Taxweb, and Paperless.",
    shortDescription: "Global tax compliance and e-invoicing platform processing 11 billion+ transactions annually across 70+ countries.",
    websiteUrl: "https://sovos.com",
    category: "E_INVOICING",
    subcategories: ["E-Invoicing", "Tax Compliance", "Tax Reporting", "Regulatory Intelligence"],
    pricingModel: "CONTACT_SALES",
    hasFreeTrialOrTier: false,
    frameworksSupported: ["EU VAT Directive", "Peppol", "ViDA", "SAF-T", "SII", "CFDI", "CTe/NFe"],
    deploymentsSupported: ["Cloud"],
    integrationsSupported: ["SAP", "Oracle", "Microsoft Dynamics", "Workday", "NetSuite"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: true,
    overallScore: 8.4,
    easeOfUse: 7.5,
    featureRichness: 9.0,
    valueForMoney: 7.0,
    customerSupport: 8.0,
    keyFeatures: ["Global e-invoicing compliance", "Tax determination", "Regulatory reporting", "Real-time mandate tracking", "Digital tax filing", "Continuous transaction controls", "Multi-country VAT compliance"],
    companySize: "Enterprise",
    foundedYear: 1979,
    headquarters: "Boston, MA",
    employeeCount: "1,001-5,000",
    isPublished: true,
    isFeatured: true,
  },
  {
    name: "Pagero",
    slug: "pagero",
    description: "Pagero, now part of Thomson Reuters, operates one of the world's largest open business networks for e-invoicing and document exchange based on the Peppol framework. The platform connects over 200,000 businesses globally, enabling compliant electronic invoicing, purchase orders, and other business documents. Pagero specializes in helping companies meet e-invoicing mandates across Europe, Latin America, and Asia-Pacific.",
    shortDescription: "Open business network for Peppol-based e-invoicing connecting 200,000+ businesses globally.",
    websiteUrl: "https://www.pagero.com",
    category: "E_INVOICING",
    subcategories: ["E-Invoicing", "Peppol Network", "Document Exchange", "AP Automation"],
    pricingModel: "USAGE_BASED",
    hasFreeTrialOrTier: true,
    frameworksSupported: ["Peppol", "EU VAT Directive", "ViDA", "EN 16931", "SAF-T"],
    deploymentsSupported: ["Cloud"],
    integrationsSupported: ["SAP", "Oracle", "Microsoft Dynamics", "Infor", "Unit4"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: false,
    iso27001Certified: true,
    overallScore: 8.0,
    easeOfUse: 8.0,
    featureRichness: 8.0,
    valueForMoney: 8.0,
    customerSupport: 7.5,
    keyFeatures: ["Peppol Access Point", "Multi-country e-invoicing", "Business network connectivity", "Document routing", "Compliance validation", "AP/AR automation", "Real-time tax reporting"],
    companySize: "Mid-Market",
    foundedYear: 2007,
    headquarters: "Gothenburg, Sweden",
    employeeCount: "501-1,000",
    isPublished: true,
    isFeatured: false,
  },
  {
    name: "Basware",
    slug: "basware",
    description: "Basware is a global leader in purchase-to-pay and e-invoicing solutions, processing over 200 million transactions and $1 trillion in commerce annually through its network. The platform provides end-to-end procurement and AP automation with built-in e-invoicing compliance across 60+ countries. Basware's open network connects millions of buyers and suppliers worldwide.",
    shortDescription: "Purchase-to-pay and e-invoicing platform processing $1 trillion in annual commerce across 60+ countries.",
    websiteUrl: "https://www.basware.com",
    category: "E_INVOICING",
    subcategories: ["E-Invoicing", "Purchase-to-Pay", "AP Automation", "Procurement"],
    pricingModel: "CONTACT_SALES",
    hasFreeTrialOrTier: false,
    frameworksSupported: ["Peppol", "EU VAT Directive", "EN 16931", "ViDA"],
    deploymentsSupported: ["Cloud"],
    integrationsSupported: ["SAP", "Oracle", "Microsoft Dynamics", "Workday", "NetSuite"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: true,
    overallScore: 8.0,
    easeOfUse: 7.5,
    featureRichness: 8.5,
    valueForMoney: 7.0,
    customerSupport: 7.5,
    keyFeatures: ["E-invoicing compliance", "Purchase-to-pay automation", "AP automation", "Open business network", "Spend analytics", "Contract management", "Supplier portal"],
    companySize: "Enterprise",
    foundedYear: 1985,
    headquarters: "Espoo, Finland",
    employeeCount: "1,001-5,000",
    isPublished: true,
    isFeatured: false,
  },
  {
    name: "Tungsten Network",
    slug: "tungsten-network",
    description: "Tungsten Network, now part of Corcentric, is one of the world's largest compliant e-invoicing networks, processing invoices in over 40 countries for major corporations. The platform specializes in ensuring invoices meet local tax authority requirements and provides automated validation, routing, and compliance checking for cross-border transactions.",
    shortDescription: "Global compliant e-invoicing network processing invoices in 40+ countries with automated tax validation.",
    websiteUrl: "https://www.tungsten-network.com",
    category: "E_INVOICING",
    subcategories: ["E-Invoicing", "Invoice Automation", "Compliance Validation"],
    pricingModel: "USAGE_BASED",
    hasFreeTrialOrTier: false,
    frameworksSupported: ["Peppol", "EU VAT Directive", "EN 16931"],
    deploymentsSupported: ["Cloud"],
    integrationsSupported: ["SAP", "Oracle", "Microsoft Dynamics"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: false,
    iso27001Certified: true,
    overallScore: 7.5,
    easeOfUse: 7.0,
    featureRichness: 7.5,
    valueForMoney: 7.0,
    customerSupport: 7.0,
    keyFeatures: ["Compliant e-invoicing", "Multi-country invoice validation", "Automated tax compliance", "Supplier onboarding", "AP workflow automation", "Invoice analytics"],
    companySize: "Enterprise",
    foundedYear: 2000,
    headquarters: "London, UK",
    employeeCount: "501-1,000",
    isPublished: true,
    isFeatured: false,
  },
  {
    name: "Coupa",
    slug: "coupa",
    description: "Coupa is a leading cloud-based business spend management (BSM) platform that includes comprehensive e-invoicing capabilities. Acquired by Thoma Bravo in 2023 for $8 billion, Coupa serves over 3,000 customers managing over $6 trillion in cumulative spend. The platform covers procurement, invoicing, expenses, payments, and supply chain, with built-in compliance for e-invoicing mandates globally.",
    shortDescription: "Cloud BSM platform managing $6 trillion+ in cumulative spend with built-in e-invoicing compliance.",
    websiteUrl: "https://www.coupa.com",
    category: "E_INVOICING",
    subcategories: ["Business Spend Management", "E-Invoicing", "Procurement", "AP Automation"],
    pricingModel: "ENTERPRISE_ONLY",
    hasFreeTrialOrTier: false,
    frameworksSupported: ["SOX", "Peppol", "EU VAT Directive", "GAAP"],
    deploymentsSupported: ["Cloud"],
    integrationsSupported: ["SAP", "Oracle", "Workday", "Microsoft Dynamics", "NetSuite", "Salesforce"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: true,
    overallScore: 8.5,
    easeOfUse: 8.0,
    featureRichness: 9.0,
    valueForMoney: 7.0,
    customerSupport: 8.0,
    keyFeatures: ["Business spend management", "E-invoicing compliance", "Procurement automation", "Expense management", "Supply chain visibility", "AI-powered insights", "Payment automation"],
    companySize: "Enterprise",
    foundedYear: 2006,
    headquarters: "San Mateo, CA",
    employeeCount: "5,001-10,000",
    isPublished: true,
    isFeatured: true,
  },
  {
    name: "TaxJar",
    slug: "taxjar",
    description: "TaxJar, a Stripe company since 2021, is a cloud-based sales tax automation platform designed for ecommerce businesses and SMBs. The platform automates sales tax calculations, nexus tracking, filing, and remittance across all US states and territories. TaxJar's API-first approach makes it popular among developers and online retailers looking for lightweight, accurate tax compliance.",
    shortDescription: "Stripe-owned sales tax automation platform for ecommerce with API-first design and automated filing.",
    websiteUrl: "https://www.taxjar.com",
    category: "TAX_COMPLIANCE",
    subcategories: ["Sales Tax", "Tax Filing", "Nexus Tracking", "Ecommerce Tax"],
    pricingModel: "SUBSCRIPTION",
    hasFreeTrialOrTier: true,
    frameworksSupported: ["US Sales Tax", "Marketplace Facilitator Laws"],
    deploymentsSupported: ["Cloud"],
    integrationsSupported: ["Stripe", "Shopify", "Amazon", "WooCommerce", "BigCommerce", "Magento", "QuickBooks"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: false,
    overallScore: 8.0,
    easeOfUse: 9.0,
    featureRichness: 7.5,
    valueForMoney: 8.5,
    customerSupport: 7.5,
    keyFeatures: ["Sales tax calculation API", "Automated tax filing", "Nexus tracking", "Economic nexus insights", "Exemption certificates", "Multi-channel support", "Real-time tax rates"],
    companySize: "SMB",
    foundedYear: 2013,
    headquarters: "Boston, MA",
    employeeCount: "201-500",
    isPublished: true,
    isFeatured: false,
  },
  {
    name: "Thomson Reuters ONESOURCE",
    slug: "thomson-reuters-onesource",
    description: "Thomson Reuters ONESOURCE is a comprehensive suite of corporate tax technology solutions used by tax departments at the world's largest companies. ONESOURCE covers indirect tax determination, direct tax compliance and provision, transfer pricing, and statutory reporting. The platform supports tax operations in over 200 jurisdictions worldwide and is deeply integrated with major ERP systems.",
    shortDescription: "Comprehensive corporate tax technology suite covering 200+ jurisdictions for the world's largest enterprises.",
    websiteUrl: "https://tax.thomsonreuters.com/en/onesource",
    category: "TAX_COMPLIANCE",
    subcategories: ["Corporate Tax", "Indirect Tax", "Transfer Pricing", "Tax Provision"],
    pricingModel: "ENTERPRISE_ONLY",
    hasFreeTrialOrTier: false,
    frameworksSupported: ["SOX", "GAAP", "IFRS", "OECD BEPS", "EU VAT Directive", "Pillar Two"],
    deploymentsSupported: ["Cloud", "On-Premise", "Hybrid"],
    integrationsSupported: ["SAP", "Oracle", "Microsoft Dynamics", "Workday", "JD Edwards"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: true,
    overallScore: 9.0,
    easeOfUse: 7.0,
    featureRichness: 9.5,
    valueForMoney: 7.0,
    customerSupport: 8.5,
    keyFeatures: ["Indirect tax determination", "Tax provision (ASC 740)", "Transfer pricing documentation", "Statutory reporting", "Tax data analytics", "Global compliance", "Workflow automation"],
    companySize: "Enterprise",
    foundedYear: 2006,
    headquarters: "Stamford, CT",
    employeeCount: "10,000+",
    isPublished: true,
    isFeatured: true,
  },
  {
    name: "Wolters Kluwer CCH",
    slug: "wolters-kluwer-cch",
    description: "Wolters Kluwer CCH is a division of the Dutch information services company providing tax, accounting, and audit software used by corporate tax departments and accounting firms worldwide. CCH Tagetik handles corporate performance management and tax provision, while CCH Axcess and CCH OneClick support tax preparation and compliance workflows. The platform is trusted by Big Four firms and Fortune 500 companies.",
    shortDescription: "Global tax and accounting software platform trusted by Big Four firms and Fortune 500 corporate tax departments.",
    websiteUrl: "https://www.wolterskluwer.com/en/solutions/cch-tagetik",
    category: "TAX_COMPLIANCE",
    subcategories: ["Tax Provision", "Tax Compliance", "Accounting", "Audit"],
    pricingModel: "ENTERPRISE_ONLY",
    hasFreeTrialOrTier: false,
    frameworksSupported: ["SOX", "GAAP", "IFRS", "OECD BEPS", "Pillar Two", "EU VAT Directive"],
    deploymentsSupported: ["Cloud", "On-Premise", "Hybrid"],
    integrationsSupported: ["SAP", "Oracle", "Microsoft Dynamics", "Workday"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: true,
    overallScore: 8.8,
    easeOfUse: 7.0,
    featureRichness: 9.5,
    valueForMoney: 7.0,
    customerSupport: 8.0,
    keyFeatures: ["Tax provision (ASC 740/IAS 12)", "Corporate tax compliance", "Transfer pricing", "Statutory reporting", "Tax analytics", "Audit workflow management", "Regulatory content updates"],
    companySize: "Enterprise",
    foundedYear: 1913,
    headquarters: "Alphen aan den Rijn, Netherlands",
    employeeCount: "10,000+",
    isPublished: true,
    isFeatured: true,
  },
  {
    name: "Comarch E-Invoicing",
    slug: "comarch-e-invoicing",
    description: "Comarch is a Polish IT company that has become a major player in European e-invoicing, particularly through its support for Poland's KSeF (National E-Invoicing System) mandate. Comarch's e-invoicing solutions support Peppol, CIUS formats, and country-specific mandates across Europe. The platform handles document exchange, archiving, and compliance validation for businesses of all sizes.",
    shortDescription: "European e-invoicing specialist with deep KSeF (Poland) expertise and Peppol network support.",
    websiteUrl: "https://www.comarch.com/e-invoicing/",
    category: "E_INVOICING",
    subcategories: ["E-Invoicing", "KSeF Compliance", "Peppol", "Document Archiving"],
    pricingModel: "SUBSCRIPTION",
    hasFreeTrialOrTier: true,
    frameworksSupported: ["Peppol", "KSeF", "EN 16931", "EU VAT Directive", "ViDA"],
    deploymentsSupported: ["Cloud", "On-Premise"],
    integrationsSupported: ["SAP", "Oracle", "Microsoft Dynamics", "Comarch ERP"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: false,
    iso27001Certified: true,
    overallScore: 7.5,
    easeOfUse: 7.5,
    featureRichness: 8.0,
    valueForMoney: 8.0,
    customerSupport: 7.0,
    keyFeatures: ["KSeF compliance", "Peppol Access Point", "Multi-format support", "E-archiving", "Document validation", "EDI integration", "Country-specific compliance"],
    companySize: "Mid-Market",
    foundedYear: 1993,
    headquarters: "Krakow, Poland",
    employeeCount: "5,001-10,000",
    isPublished: true,
    isFeatured: false,
  },
  {
    name: "SAP Document Compliance",
    slug: "sap-document-compliance",
    description: "SAP Document and Reporting Compliance is SAP's native e-invoicing and tax reporting solution embedded within the SAP ecosystem. The platform supports continuous transaction controls (CTC), real-time e-invoicing mandates, and statutory reporting requirements across 60+ countries. As a native SAP solution, it provides seamless integration with S/4HANA and SAP ECC for enterprises already running SAP.",
    shortDescription: "SAP-native e-invoicing and tax reporting compliance solution supporting mandates in 60+ countries.",
    websiteUrl: "https://www.sap.com/products/financial-management/document-compliance.html",
    category: "E_INVOICING",
    subcategories: ["E-Invoicing", "Tax Reporting", "Statutory Compliance", "CTC"],
    pricingModel: "ENTERPRISE_ONLY",
    hasFreeTrialOrTier: false,
    frameworksSupported: ["Peppol", "EU VAT Directive", "ViDA", "SAF-T", "SII", "CFDI", "KSeF"],
    deploymentsSupported: ["Cloud", "On-Premise", "Hybrid"],
    integrationsSupported: ["SAP S/4HANA", "SAP ECC", "SAP Business One", "SAP Ariba"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: true,
    overallScore: 8.5,
    easeOfUse: 7.0,
    featureRichness: 9.0,
    valueForMoney: 7.0,
    customerSupport: 8.0,
    keyFeatures: ["Native SAP integration", "Real-time e-invoicing", "Continuous transaction controls", "Statutory reporting", "Multi-country mandate support", "E-document archiving", "Automated tax determination"],
    companySize: "Enterprise",
    foundedYear: 1972,
    headquarters: "Walldorf, Germany",
    employeeCount: "10,000+",
    isPublished: true,
    isFeatured: true,
  },

  // ============================================
  // CYBERSECURITY (12 vendors)
  // ============================================
  {
    name: "CrowdStrike",
    slug: "crowdstrike",
    description: "CrowdStrike is a leading cybersecurity company providing cloud-native endpoint protection, threat intelligence, and incident response services through its Falcon platform. Founded by former McAfee executives, CrowdStrike pioneered the concept of cloud-delivered endpoint security and now protects workloads across endpoints, cloud, identity, and data. The company is publicly traded (NASDAQ: CRWD) and serves over 29,000 customers worldwide.",
    shortDescription: "Cloud-native endpoint protection platform serving 29,000+ customers with AI-powered threat detection.",
    websiteUrl: "https://www.crowdstrike.com",
    category: "ENDPOINT_SECURITY",
    subcategories: ["Endpoint Protection", "Threat Intelligence", "Incident Response", "Cloud Security"],
    pricingModel: "PER_SEAT",
    hasFreeTrialOrTier: true,
    frameworksSupported: ["NIST CSF", "SOC 2", "ISO 27001", "PCI DSS", "HIPAA", "FedRAMP", "CMMC"],
    deploymentsSupported: ["Cloud"],
    integrationsSupported: ["Splunk", "AWS", "Azure", "GCP", "ServiceNow", "Okta", "Zscaler", "Palo Alto Networks"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: true,
    overallScore: 9.2,
    easeOfUse: 8.5,
    featureRichness: 9.5,
    valueForMoney: 7.5,
    customerSupport: 8.5,
    keyFeatures: ["Falcon endpoint protection", "AI-powered threat detection", "Managed threat hunting", "Cloud workload protection", "Identity threat detection", "Threat intelligence", "Incident response services"],
    companySize: "Enterprise",
    foundedYear: 2011,
    headquarters: "Austin, TX",
    employeeCount: "5,001-10,000",
    isPublished: true,
    isFeatured: true,
  },
  {
    name: "Palo Alto Networks",
    slug: "palo-alto-networks",
    description: "Palo Alto Networks is the world's largest pure-play cybersecurity company, offering a comprehensive portfolio spanning network security, cloud security, and security operations. Its Prisma Cloud platform leads in cloud-native application protection (CNAPP), while its Strata firewalls and Cortex XDR/XSIAM platforms provide network and endpoint security. The company serves over 80,000 customers across 150+ countries.",
    shortDescription: "World's largest cybersecurity company with leading network, cloud, and security operations platforms.",
    websiteUrl: "https://www.paloaltonetworks.com",
    category: "CLOUD_SECURITY",
    subcategories: ["Network Security", "Cloud Security", "CNAPP", "XDR", "SASE"],
    pricingModel: "CONTACT_SALES",
    hasFreeTrialOrTier: true,
    frameworksSupported: ["NIST CSF", "SOC 2", "ISO 27001", "PCI DSS", "HIPAA", "FedRAMP", "CIS Benchmarks"],
    deploymentsSupported: ["Cloud", "On-Premise", "Hybrid"],
    integrationsSupported: ["AWS", "Azure", "GCP", "Splunk", "ServiceNow", "Okta", "CrowdStrike"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: true,
    overallScore: 9.3,
    easeOfUse: 7.5,
    featureRichness: 9.8,
    valueForMoney: 7.0,
    customerSupport: 8.5,
    keyFeatures: ["Prisma Cloud CNAPP", "Next-gen firewalls", "Cortex XDR/XSIAM", "SASE/Prisma Access", "Cloud security posture management", "AI-driven security operations", "Threat intelligence (Unit 42)"],
    companySize: "Enterprise",
    foundedYear: 2005,
    headquarters: "Santa Clara, CA",
    employeeCount: "10,000+",
    isPublished: true,
    isFeatured: true,
  },
  {
    name: "Qualys",
    slug: "qualys",
    description: "Qualys is a pioneer in cloud-based IT security and compliance solutions, providing its TotalCloud platform for vulnerability management, policy compliance, and cloud security. Founded in 1999, Qualys was one of the first companies to deliver security as a service and now scans over 1 billion IP addresses per year. The platform provides continuous monitoring and assessment across on-premise, cloud, and container environments.",
    shortDescription: "Pioneer in cloud-based vulnerability management and compliance scanning over 1 billion IPs annually.",
    websiteUrl: "https://www.qualys.com",
    category: "CLOUD_SECURITY",
    subcategories: ["Vulnerability Management", "Policy Compliance", "Web Application Security", "Container Security"],
    pricingModel: "SUBSCRIPTION",
    hasFreeTrialOrTier: true,
    frameworksSupported: ["NIST CSF", "SOC 2", "ISO 27001", "PCI DSS", "HIPAA", "CIS Benchmarks", "FedRAMP"],
    deploymentsSupported: ["Cloud"],
    integrationsSupported: ["AWS", "Azure", "GCP", "ServiceNow", "Splunk", "Jira", "Jenkins"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: true,
    overallScore: 8.5,
    easeOfUse: 8.0,
    featureRichness: 8.5,
    valueForMoney: 8.0,
    customerSupport: 7.5,
    keyFeatures: ["Vulnerability management (VMDR)", "Policy compliance", "Web application scanning", "Container security", "Cloud security assessment", "Patch management", "Asset inventory"],
    companySize: "Enterprise",
    foundedYear: 1999,
    headquarters: "Foster City, CA",
    employeeCount: "1,001-5,000",
    isPublished: true,
    isFeatured: false,
  },
  {
    name: "Tenable",
    slug: "tenable",
    description: "Tenable is a leading exposure management company known for its Nessus vulnerability scanner and Tenable One platform. The company helps over 44,000 organizations understand and reduce their cyber risk by providing visibility across IT infrastructure, cloud environments, containers, web applications, and identity systems. Tenable's products are widely used for compliance scanning and vulnerability prioritization.",
    shortDescription: "Exposure management platform with the industry-leading Nessus scanner serving 44,000+ organizations.",
    websiteUrl: "https://www.tenable.com",
    category: "CLOUD_SECURITY",
    subcategories: ["Vulnerability Management", "Exposure Management", "OT Security", "Cloud Security"],
    pricingModel: "SUBSCRIPTION",
    hasFreeTrialOrTier: true,
    frameworksSupported: ["NIST CSF", "SOC 2", "ISO 27001", "PCI DSS", "HIPAA", "CIS Benchmarks"],
    deploymentsSupported: ["Cloud", "On-Premise", "Hybrid"],
    integrationsSupported: ["AWS", "Azure", "GCP", "Splunk", "ServiceNow", "Jira", "Cisco"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: true,
    overallScore: 8.6,
    easeOfUse: 8.0,
    featureRichness: 8.5,
    valueForMoney: 8.0,
    customerSupport: 8.0,
    keyFeatures: ["Nessus vulnerability scanner", "Exposure management", "Cloud security posture", "OT/IoT security", "Identity exposure", "Attack path analysis", "Risk-based prioritization"],
    companySize: "Enterprise",
    foundedYear: 2002,
    headquarters: "Columbia, MD",
    employeeCount: "1,001-5,000",
    isPublished: true,
    isFeatured: false,
  },
  {
    name: "Zscaler",
    slug: "zscaler",
    description: "Zscaler is the leader in cloud-based zero trust security, operating the world's largest inline security cloud that processes over 400 billion transactions daily. The Zscaler Zero Trust Exchange platform provides secure internet access (ZIA), private access to applications (ZPA), and digital experience monitoring. Zscaler eliminates the need for traditional VPNs and firewalls, providing security that follows users regardless of location.",
    shortDescription: "World's largest zero trust security cloud processing 400 billion+ daily transactions.",
    websiteUrl: "https://www.zscaler.com",
    category: "CLOUD_SECURITY",
    subcategories: ["Zero Trust", "SASE", "Secure Web Gateway", "ZTNA"],
    pricingModel: "PER_SEAT",
    hasFreeTrialOrTier: false,
    frameworksSupported: ["NIST CSF", "SOC 2", "ISO 27001", "FedRAMP", "HIPAA", "PCI DSS"],
    deploymentsSupported: ["Cloud"],
    integrationsSupported: ["AWS", "Azure", "GCP", "CrowdStrike", "Okta", "Microsoft 365", "Splunk", "ServiceNow"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: true,
    overallScore: 9.0,
    easeOfUse: 8.5,
    featureRichness: 9.0,
    valueForMoney: 7.5,
    customerSupport: 8.0,
    keyFeatures: ["Zero Trust Exchange", "Secure Internet Access (ZIA)", "Zero Trust Network Access (ZPA)", "Digital experience monitoring", "Data loss prevention", "Cloud firewall", "Browser isolation"],
    companySize: "Enterprise",
    foundedYear: 2007,
    headquarters: "San Jose, CA",
    employeeCount: "5,001-10,000",
    isPublished: true,
    isFeatured: true,
  },
  {
    name: "Fortinet",
    slug: "fortinet",
    description: "Fortinet is a multinational cybersecurity company providing network security appliances, unified threat management, and a broad security fabric architecture. Its flagship FortiGate firewalls are among the most widely deployed in the world, and the Fortinet Security Fabric integrates over 50 security and networking products. Fortinet serves over 755,000 customers and holds the most networking and security patents in the industry.",
    shortDescription: "Cybersecurity leader with 755,000+ customers and the most widely deployed next-gen firewalls globally.",
    websiteUrl: "https://www.fortinet.com",
    category: "CLOUD_SECURITY",
    subcategories: ["Network Security", "Firewall", "SD-WAN", "SASE", "OT Security"],
    pricingModel: "CONTACT_SALES",
    hasFreeTrialOrTier: true,
    frameworksSupported: ["NIST CSF", "SOC 2", "ISO 27001", "PCI DSS", "HIPAA", "FedRAMP", "CMMC"],
    deploymentsSupported: ["Cloud", "On-Premise", "Hybrid"],
    integrationsSupported: ["AWS", "Azure", "GCP", "VMware", "ServiceNow", "Splunk"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: true,
    overallScore: 8.8,
    easeOfUse: 7.5,
    featureRichness: 9.0,
    valueForMoney: 8.5,
    customerSupport: 8.0,
    keyFeatures: ["FortiGate next-gen firewalls", "Security Fabric architecture", "SD-WAN", "SASE", "FortiEDR endpoint protection", "OT/IoT security", "AI-driven threat intelligence"],
    companySize: "Enterprise",
    foundedYear: 2000,
    headquarters: "Sunnyvale, CA",
    employeeCount: "10,000+",
    isPublished: true,
    isFeatured: true,
  },
  {
    name: "KnowBe4",
    slug: "knowbe4",
    description: "KnowBe4 is the world's largest security awareness training and simulated phishing platform. Founded by serial entrepreneur Stu Sjouwerman and legendary hacker Kevin Mitnick, KnowBe4 serves over 65,000 organizations. The platform provides a comprehensive library of training content, automated phishing simulations, and compliance training modules that help organizations reduce the risk of social engineering attacks.",
    shortDescription: "World's largest security awareness training platform serving 65,000+ organizations with phishing simulations.",
    websiteUrl: "https://www.knowbe4.com",
    category: "SECURITY_AWARENESS",
    subcategories: ["Security Awareness Training", "Phishing Simulation", "Compliance Training"],
    pricingModel: "PER_SEAT",
    hasFreeTrialOrTier: true,
    frameworksSupported: ["NIST CSF", "SOC 2", "ISO 27001", "PCI DSS", "HIPAA", "GDPR"],
    deploymentsSupported: ["Cloud"],
    integrationsSupported: ["Microsoft 365", "Google Workspace", "Okta", "Azure AD", "Slack", "Teams"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: true,
    overallScore: 8.7,
    easeOfUse: 9.0,
    featureRichness: 8.5,
    valueForMoney: 8.5,
    customerSupport: 8.5,
    keyFeatures: ["Simulated phishing campaigns", "Security awareness training library", "Compliance training modules", "Risk scoring", "Phish Alert Button", "AI-driven training recommendations", "Reporting & analytics dashboard"],
    companySize: "Mid-Market",
    foundedYear: 2010,
    headquarters: "Clearwater, FL",
    employeeCount: "1,001-5,000",
    isPublished: true,
    isFeatured: true,
  },
  {
    name: "Proofpoint",
    slug: "proofpoint",
    description: "Proofpoint is a leading cybersecurity company focused on protecting organizations from advanced threats targeting people via email, social media, and mobile. Acquired by Thoma Bravo in 2021 for $12.3 billion, Proofpoint serves over 8,000 enterprise customers including 83% of the Fortune 100. The platform provides email security, data loss prevention, security awareness training, and compliance archiving solutions.",
    shortDescription: "People-centric cybersecurity platform protecting 83% of the Fortune 100 from email and social threats.",
    websiteUrl: "https://www.proofpoint.com",
    category: "CLOUD_SECURITY",
    subcategories: ["Email Security", "Data Loss Prevention", "Security Awareness", "Compliance Archiving"],
    pricingModel: "PER_SEAT",
    hasFreeTrialOrTier: false,
    frameworksSupported: ["NIST CSF", "SOC 2", "ISO 27001", "HIPAA", "PCI DSS", "GDPR", "FedRAMP"],
    deploymentsSupported: ["Cloud", "Hybrid"],
    integrationsSupported: ["Microsoft 365", "Google Workspace", "Splunk", "CrowdStrike", "Okta", "ServiceNow"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: true,
    overallScore: 8.8,
    easeOfUse: 8.0,
    featureRichness: 9.0,
    valueForMoney: 7.5,
    customerSupport: 8.0,
    keyFeatures: ["Advanced email protection", "Targeted attack protection", "Data loss prevention", "Security awareness training", "Email fraud defense", "Compliance archiving", "Insider threat management"],
    companySize: "Enterprise",
    foundedYear: 2002,
    headquarters: "Sunnyvale, CA",
    employeeCount: "5,001-10,000",
    isPublished: true,
    isFeatured: true,
  },
  {
    name: "Rapid7",
    slug: "rapid7",
    description: "Rapid7 provides cybersecurity analytics and automation solutions through its Insight Platform, enabling organizations to detect and respond to threats, manage vulnerabilities, and monitor compliance. The platform includes InsightVM for vulnerability management, InsightIDR for SIEM/XDR, and InsightConnect for SOAR. Rapid7 also maintains the popular Metasploit open-source penetration testing framework.",
    shortDescription: "Cybersecurity analytics platform with vulnerability management, XDR, and the Metasploit framework.",
    websiteUrl: "https://www.rapid7.com",
    category: "CLOUD_SECURITY",
    subcategories: ["Vulnerability Management", "SIEM", "XDR", "SOAR", "Penetration Testing"],
    pricingModel: "SUBSCRIPTION",
    hasFreeTrialOrTier: true,
    frameworksSupported: ["NIST CSF", "SOC 2", "ISO 27001", "PCI DSS", "HIPAA", "CIS Benchmarks"],
    deploymentsSupported: ["Cloud", "On-Premise", "Hybrid"],
    integrationsSupported: ["AWS", "Azure", "GCP", "Splunk", "ServiceNow", "Jira", "Slack"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: true,
    overallScore: 8.3,
    easeOfUse: 8.0,
    featureRichness: 8.5,
    valueForMoney: 8.0,
    customerSupport: 7.5,
    keyFeatures: ["InsightVM vulnerability management", "InsightIDR XDR/SIEM", "InsightConnect SOAR", "Metasploit penetration testing", "Cloud risk assessment", "Threat intelligence", "Compliance reporting"],
    companySize: "Enterprise",
    foundedYear: 2000,
    headquarters: "Boston, MA",
    employeeCount: "1,001-5,000",
    isPublished: true,
    isFeatured: false,
  },
  {
    name: "SentinelOne",
    slug: "sentinelone",
    description: "SentinelOne is an AI-powered cybersecurity company providing autonomous endpoint protection, detection, and response through its Singularity XDR platform. The platform uses behavioral AI to detect and respond to threats in real-time without requiring human intervention. SentinelOne also offers cloud workload protection, identity security, and its Purple AI security analyst. The company went public in 2021 and serves thousands of enterprise customers.",
    shortDescription: "AI-powered autonomous endpoint protection and XDR platform with real-time behavioral threat detection.",
    websiteUrl: "https://www.sentinelone.com",
    category: "ENDPOINT_SECURITY",
    subcategories: ["Endpoint Protection", "XDR", "Cloud Workload Protection", "Identity Security"],
    pricingModel: "PER_SEAT",
    hasFreeTrialOrTier: true,
    frameworksSupported: ["NIST CSF", "SOC 2", "ISO 27001", "PCI DSS", "HIPAA", "FedRAMP"],
    deploymentsSupported: ["Cloud", "Hybrid"],
    integrationsSupported: ["AWS", "Azure", "GCP", "Splunk", "ServiceNow", "Okta", "CrowdStrike"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: true,
    overallScore: 8.8,
    easeOfUse: 8.5,
    featureRichness: 9.0,
    valueForMoney: 8.0,
    customerSupport: 8.0,
    keyFeatures: ["Singularity XDR platform", "Autonomous threat response", "Behavioral AI engine", "Cloud workload protection", "Purple AI security analyst", "Identity threat detection", "Ransomware rollback"],
    companySize: "Enterprise",
    foundedYear: 2013,
    headquarters: "Mountain View, CA",
    employeeCount: "1,001-5,000",
    isPublished: true,
    isFeatured: true,
  },
  {
    name: "Wiz",
    slug: "wiz",
    description: "Wiz is the fastest-growing cloud security company in history, reaching $100M ARR in just 18 months after launch. The agentless cloud security platform provides full-stack visibility across AWS, Azure, GCP, and Kubernetes, identifying toxic combinations of risks across misconfigurations, vulnerabilities, exposed secrets, and identity issues. Wiz was acquired by Google/Alphabet in 2025 for $32 billion.",
    shortDescription: "Fastest-growing cloud security platform providing agentless full-stack visibility across multi-cloud environments.",
    websiteUrl: "https://www.wiz.io",
    category: "CLOUD_SECURITY",
    subcategories: ["CNAPP", "CSPM", "CWPP", "DSPM", "Kubernetes Security"],
    pricingModel: "CONTACT_SALES",
    hasFreeTrialOrTier: true,
    frameworksSupported: ["NIST CSF", "SOC 2", "ISO 27001", "PCI DSS", "HIPAA", "CIS Benchmarks", "GDPR"],
    deploymentsSupported: ["Cloud"],
    integrationsSupported: ["AWS", "Azure", "GCP", "Kubernetes", "Terraform", "Jira", "Slack", "ServiceNow", "Splunk"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: true,
    overallScore: 9.4,
    easeOfUse: 9.5,
    featureRichness: 9.5,
    valueForMoney: 8.0,
    customerSupport: 8.5,
    keyFeatures: ["Agentless cloud scanning", "Security graph visualization", "Toxic combination detection", "CSPM & CWPP unified", "Container & Kubernetes security", "Data security posture management", "AI security posture management"],
    companySize: "Enterprise",
    foundedYear: 2020,
    headquarters: "New York, NY",
    employeeCount: "1,001-5,000",
    isPublished: true,
    isFeatured: true,
  },
  {
    name: "Snyk",
    slug: "snyk",
    description: "Snyk is a developer-first application security platform that helps development teams find, prioritize, and fix security vulnerabilities in code, open-source dependencies, containers, and infrastructure as code. With over 3 million developers using the platform, Snyk integrates directly into the developer workflow through IDE plugins, CI/CD pipelines, and source control management. The company serves enterprises like Google, Salesforce, and Intuit.",
    shortDescription: "Developer-first application security platform used by 3 million+ developers to find and fix code vulnerabilities.",
    websiteUrl: "https://snyk.io",
    category: "APPLICATION_SECURITY",
    subcategories: ["SAST", "SCA", "Container Security", "IaC Security"],
    pricingModel: "FREEMIUM",
    hasFreeTrialOrTier: true,
    frameworksSupported: ["NIST CSF", "SOC 2", "ISO 27001", "PCI DSS", "OWASP Top 10"],
    deploymentsSupported: ["Cloud", "On-Premise"],
    integrationsSupported: ["GitHub", "GitLab", "Bitbucket", "Jira", "Jenkins", "Docker", "Kubernetes", "AWS", "Azure"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: true,
    overallScore: 8.7,
    easeOfUse: 9.0,
    featureRichness: 8.5,
    valueForMoney: 8.5,
    customerSupport: 8.0,
    keyFeatures: ["Open-source vulnerability scanning", "Code security analysis (SAST)", "Container image scanning", "IaC security scanning", "License compliance", "Developer IDE integration", "CI/CD pipeline security"],
    companySize: "Enterprise",
    foundedYear: 2015,
    headquarters: "Boston, MA",
    employeeCount: "1,001-5,000",
    isPublished: true,
    isFeatured: true,
  },

  // ============================================
  // DATA PRIVACY (8 vendors)
  // ============================================
  {
    name: "BigID",
    slug: "bigid",
    description: "BigID is a leading data intelligence platform that helps organizations discover, manage, protect, and get more value from their personal and sensitive data. The platform uses advanced ML and AI to provide data discovery, classification, cataloging, and privacy management at enterprise scale. BigID serves Fortune 500 companies across financial services, healthcare, retail, and technology sectors.",
    shortDescription: "AI-powered data intelligence platform for discovery, classification, and privacy management at enterprise scale.",
    websiteUrl: "https://bigid.com",
    category: "PRIVACY_COMPLIANCE",
    subcategories: ["Data Discovery", "Data Classification", "Privacy Management", "Data Governance"],
    pricingModel: "CONTACT_SALES",
    hasFreeTrialOrTier: true,
    frameworksSupported: ["GDPR", "CCPA/CPRA", "LGPD", "HIPAA", "PCI DSS", "NIST Privacy Framework"],
    deploymentsSupported: ["Cloud", "On-Premise", "Hybrid"],
    integrationsSupported: ["AWS", "Azure", "GCP", "Snowflake", "Databricks", "OneTrust", "ServiceNow", "Salesforce"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: true,
    overallScore: 8.8,
    easeOfUse: 7.5,
    featureRichness: 9.5,
    valueForMoney: 7.0,
    customerSupport: 8.0,
    keyFeatures: ["ML-powered data discovery", "Automated data classification", "Privacy impact assessments", "Data risk scoring", "Data catalog", "Consent & preference management", "DSAR automation"],
    companySize: "Enterprise",
    foundedYear: 2016,
    headquarters: "New York, NY",
    employeeCount: "501-1,000",
    isPublished: true,
    isFeatured: true,
  },
  {
    name: "TrustArc",
    slug: "trustarc",
    description: "TrustArc is one of the longest-standing privacy management platforms, providing comprehensive privacy compliance solutions including assessments, consent management, and data subject rights automation. Formerly known as TRUSTe, the company has been in the privacy space since 1997 and serves over 5,000 customers. TrustArc's platform combines technology with privacy expertise to help organizations operationalize privacy compliance across global regulations.",
    shortDescription: "Veteran privacy management platform serving 5,000+ customers with assessments, consent, and DSAR automation.",
    websiteUrl: "https://trustarc.com",
    category: "PRIVACY_COMPLIANCE",
    subcategories: ["Privacy Management", "Consent Management", "Privacy Assessments", "Cookie Compliance"],
    pricingModel: "SUBSCRIPTION",
    hasFreeTrialOrTier: false,
    frameworksSupported: ["GDPR", "CCPA/CPRA", "LGPD", "PIPEDA", "APPI", "PDPA", "HIPAA"],
    deploymentsSupported: ["Cloud"],
    integrationsSupported: ["OneTrust", "ServiceNow", "Salesforce", "SAP", "Adobe"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: false,
    overallScore: 8.0,
    easeOfUse: 7.5,
    featureRichness: 8.5,
    valueForMoney: 7.5,
    customerSupport: 8.0,
    keyFeatures: ["Privacy impact assessments", "Cookie consent management", "DSAR workflow automation", "Data inventory mapping", "Vendor risk management", "Privacy program benchmarking", "Regulatory intelligence"],
    companySize: "Enterprise",
    foundedYear: 1997,
    headquarters: "San Francisco, CA",
    employeeCount: "201-500",
    isPublished: true,
    isFeatured: false,
  },
  {
    name: "Cookiebot",
    slug: "cookiebot",
    description: "Cookiebot by Usercentrics is a widely-used consent management platform (CMP) that helps websites comply with cookie consent regulations including GDPR, ePrivacy Directive, and CCPA. The platform automatically scans websites for cookies and trackers, generates compliant consent banners, and manages user preferences. Cookiebot serves over 1.4 million websites and is an IAB TCF certified CMP.",
    shortDescription: "Leading consent management platform automatically scanning cookies on 1.4 million+ websites for GDPR compliance.",
    websiteUrl: "https://www.cookiebot.com",
    category: "CONSENT_MANAGEMENT",
    subcategories: ["Cookie Consent", "Privacy Compliance", "Website Scanning", "Consent Records"],
    pricingModel: "FREEMIUM",
    hasFreeTrialOrTier: true,
    frameworksSupported: ["GDPR", "ePrivacy Directive", "CCPA/CPRA", "LGPD", "POPIA", "IAB TCF 2.2"],
    deploymentsSupported: ["Cloud"],
    integrationsSupported: ["Google Tag Manager", "WordPress", "Shopify", "Adobe Analytics", "Google Analytics"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: false,
    iso27001Certified: true,
    overallScore: 8.2,
    easeOfUse: 9.0,
    featureRichness: 7.5,
    valueForMoney: 8.5,
    customerSupport: 7.0,
    keyFeatures: ["Automatic cookie scanning", "Customizable consent banner", "IAB TCF 2.2 support", "Google Consent Mode integration", "Consent log storage", "Multi-language support", "Geolocation-based consent"],
    companySize: "SMB",
    foundedYear: 2012,
    headquarters: "Copenhagen, Denmark",
    employeeCount: "51-200",
    isPublished: true,
    isFeatured: false,
  },
  {
    name: "Osano",
    slug: "osano",
    description: "Osano is an easy-to-use data privacy platform that provides consent management, vendor monitoring, DSAR automation, and privacy assessments. Osano differentiates itself with a vendor risk monitoring feature that tracks the privacy practices of over 50,000 companies, alerting customers when vendors change their privacy policies. The platform is designed to be accessible to teams without dedicated privacy professionals.",
    shortDescription: "User-friendly data privacy platform with consent management and vendor risk monitoring across 50,000+ companies.",
    websiteUrl: "https://www.osano.com",
    category: "CONSENT_MANAGEMENT",
    subcategories: ["Consent Management", "Vendor Privacy Monitoring", "DSAR Automation", "Privacy Assessments"],
    pricingModel: "FREEMIUM",
    hasFreeTrialOrTier: true,
    frameworksSupported: ["GDPR", "CCPA/CPRA", "LGPD", "PIPEDA", "POPIA"],
    deploymentsSupported: ["Cloud"],
    integrationsSupported: ["Shopify", "WordPress", "HubSpot", "Salesforce", "Google Tag Manager"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: false,
    overallScore: 7.8,
    easeOfUse: 9.0,
    featureRichness: 7.5,
    valueForMoney: 8.5,
    customerSupport: 8.0,
    keyFeatures: ["Consent management", "Vendor risk monitoring", "DSAR automation", "Data mapping", "Privacy assessments", "Regulatory change tracking", "No-code consent banner builder"],
    companySize: "SMB",
    foundedYear: 2018,
    headquarters: "Austin, TX",
    employeeCount: "51-200",
    isPublished: true,
    isFeatured: false,
  },
  {
    name: "WireWheel",
    slug: "wirewheel",
    description: "WireWheel provides a privacy data protection platform that helps organizations discover personal data, manage consent, automate DSARs, and maintain data maps. The platform focuses on operationalizing privacy programs with workflow automation, privacy impact assessments, and compliance dashboards. WireWheel received investment from ForgePoint Capital and serves enterprises in highly regulated industries.",
    shortDescription: "Privacy data protection platform for data discovery, consent management, and DSAR automation in regulated industries.",
    websiteUrl: "https://wirewheel.io",
    category: "DSAR_AUTOMATION",
    subcategories: ["Privacy Management", "DSAR Automation", "Data Mapping", "Consent Management"],
    pricingModel: "CONTACT_SALES",
    hasFreeTrialOrTier: false,
    frameworksSupported: ["GDPR", "CCPA/CPRA", "HIPAA", "NIST Privacy Framework"],
    deploymentsSupported: ["Cloud"],
    integrationsSupported: ["AWS", "Azure", "Salesforce", "ServiceNow"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: false,
    overallScore: 7.5,
    easeOfUse: 7.5,
    featureRichness: 7.5,
    valueForMoney: 7.0,
    customerSupport: 7.5,
    keyFeatures: ["Personal data discovery", "Automated DSAR fulfillment", "Data mapping & inventory", "Privacy impact assessments", "Consent management", "Compliance dashboards", "Vendor risk assessment"],
    companySize: "Mid-Market",
    foundedYear: 2016,
    headquarters: "Washington, DC",
    employeeCount: "51-200",
    isPublished: true,
    isFeatured: false,
  },
  {
    name: "Securiti.ai",
    slug: "securiti-ai",
    description: "Securiti is a unified data intelligence platform that combines data privacy, security, compliance, and governance capabilities. The platform provides AI-powered data discovery across structured and unstructured data, automated DSARs, consent management, and data access governance. Securiti has been named a leader in multiple analyst reports and supports compliance with over 20 global privacy regulations.",
    shortDescription: "Unified data intelligence platform combining privacy, security, and governance with AI-powered data discovery.",
    websiteUrl: "https://securiti.ai",
    category: "PRIVACY_COMPLIANCE",
    subcategories: ["Data Privacy", "Data Security", "Data Governance", "Consent Management"],
    pricingModel: "CONTACT_SALES",
    hasFreeTrialOrTier: true,
    frameworksSupported: ["GDPR", "CCPA/CPRA", "LGPD", "HIPAA", "PCI DSS", "NIST Privacy Framework", "ISO 27701"],
    deploymentsSupported: ["Cloud", "Hybrid"],
    integrationsSupported: ["AWS", "Azure", "GCP", "Snowflake", "Databricks", "Salesforce", "ServiceNow", "Slack"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: true,
    overallScore: 8.5,
    easeOfUse: 8.0,
    featureRichness: 9.0,
    valueForMoney: 7.5,
    customerSupport: 8.0,
    keyFeatures: ["AI-powered data discovery", "Automated DSAR processing", "Consent lifecycle management", "Data access governance", "Privacy impact assessments", "Breach management", "Cross-regulation compliance mapping"],
    companySize: "Enterprise",
    foundedYear: 2018,
    headquarters: "San Jose, CA",
    employeeCount: "501-1,000",
    isPublished: true,
    isFeatured: true,
  },
  {
    name: "DataGrail",
    slug: "datagrail",
    description: "DataGrail is a privacy management platform purpose-built for modern data ecosystems, providing real-time data mapping, automated DSARs, and consent management. The platform connects directly to SaaS applications and internal systems via 2,000+ pre-built integrations to discover and manage personal data wherever it lives. DataGrail serves high-growth technology companies and enterprises like Salesforce, Overstock, and Databricks.",
    shortDescription: "Privacy management platform with 2,000+ integrations for real-time data mapping and automated DSARs.",
    websiteUrl: "https://www.datagrail.io",
    category: "DSAR_AUTOMATION",
    subcategories: ["Privacy Management", "DSAR Automation", "Data Mapping", "Consent Management"],
    pricingModel: "CONTACT_SALES",
    hasFreeTrialOrTier: false,
    frameworksSupported: ["GDPR", "CCPA/CPRA", "LGPD", "CPA", "CTDPA", "VCDPA"],
    deploymentsSupported: ["Cloud"],
    integrationsSupported: ["Salesforce", "HubSpot", "Zendesk", "Slack", "Snowflake", "MongoDB", "AWS", "Azure"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: false,
    overallScore: 8.3,
    easeOfUse: 8.5,
    featureRichness: 8.5,
    valueForMoney: 7.5,
    customerSupport: 8.5,
    keyFeatures: ["Real-time data mapping", "Automated DSAR fulfillment", "2,000+ SaaS integrations", "Consent management", "Privacy risk scoring", "Request tracking dashboard", "Data deletion verification"],
    companySize: "Mid-Market",
    foundedYear: 2018,
    headquarters: "San Francisco, CA",
    employeeCount: "101-200",
    isPublished: true,
    isFeatured: true,
  },
  {
    name: "Transcend",
    slug: "transcend",
    description: "Transcend is a data privacy infrastructure company that provides programmatic privacy tools for engineering and privacy teams. The platform offers data mapping, consent management, automated DSARs, and privacy-by-design tools that integrate directly into the tech stack via APIs and code. Transcend serves technology-forward companies like Groupon, Robinhood, and Clubhouse who want to build privacy into their products.",
    shortDescription: "Developer-focused data privacy infrastructure with API-first tools for programmatic privacy management.",
    websiteUrl: "https://transcend.io",
    category: "DSAR_AUTOMATION",
    subcategories: ["Privacy Infrastructure", "DSAR Automation", "Consent Management", "Data Mapping"],
    pricingModel: "SUBSCRIPTION",
    hasFreeTrialOrTier: true,
    frameworksSupported: ["GDPR", "CCPA/CPRA", "LGPD", "PIPEDA", "APPI"],
    deploymentsSupported: ["Cloud"],
    integrationsSupported: ["AWS", "Azure", "GCP", "Segment", "Amplitude", "Snowflake", "MongoDB", "PostgreSQL"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: false,
    overallScore: 8.0,
    easeOfUse: 8.5,
    featureRichness: 8.0,
    valueForMoney: 8.0,
    customerSupport: 8.0,
    keyFeatures: ["API-first privacy tools", "Automated data subject requests", "Smart data mapping", "Consent management", "Privacy-by-design framework", "Code-level data classification", "Cross-system data deletion"],
    companySize: "Mid-Market",
    foundedYear: 2017,
    headquarters: "San Francisco, CA",
    employeeCount: "101-200",
    isPublished: true,
    isFeatured: false,
  },

  // ============================================
  // ESG & SUSTAINABILITY (8 vendors)
  // ============================================
  {
    name: "Workiva",
    slug: "workiva",
    description: "Workiva is a publicly traded company (NYSE: WK) providing a cloud platform for regulatory reporting, ESG, and financial compliance. Its platform streamlines the creation, management, and filing of SEC reports, XBRL filings, and ESG disclosures. Workiva serves over 5,800 organizations including 75% of the Fortune 500, helping them collect, link, and report data across finance, sustainability, risk, and compliance functions.",
    shortDescription: "Cloud reporting platform used by 75% of Fortune 500 for SEC filings, ESG disclosures, and financial compliance.",
    websiteUrl: "https://www.workiva.com",
    category: "ESG_REPORTING",
    subcategories: ["ESG Reporting", "SEC Filing", "Financial Reporting", "Regulatory Compliance"],
    pricingModel: "SUBSCRIPTION",
    hasFreeTrialOrTier: false,
    frameworksSupported: ["SEC", "CSRD", "GRI", "SASB", "TCFD", "CDP", "EU Taxonomy", "SOX"],
    deploymentsSupported: ["Cloud"],
    integrationsSupported: ["SAP", "Oracle", "Salesforce", "Microsoft 365", "Workday", "Power BI"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: true,
    overallScore: 8.8,
    easeOfUse: 8.0,
    featureRichness: 9.0,
    valueForMoney: 7.5,
    customerSupport: 8.5,
    keyFeatures: ["Connected reporting platform", "ESG data collection & disclosure", "SEC & XBRL filing", "Audit trail & version control", "Data linking across reports", "Workflow automation", "Multi-stakeholder collaboration"],
    companySize: "Enterprise",
    foundedYear: 2008,
    headquarters: "Ames, IA",
    employeeCount: "1,001-5,000",
    isPublished: true,
    isFeatured: true,
  },
  {
    name: "Persefoni",
    slug: "persefoni",
    description: "Persefoni is a leading climate management and accounting platform (CMAP) that helps organizations measure, manage, and report their carbon footprint. The platform automates greenhouse gas calculations aligned with the GHG Protocol and supports disclosure frameworks including CDP, TCFD, CSRD, and SEC climate rules. Persefoni serves enterprises, financial institutions, and asset managers tracking financed emissions.",
    shortDescription: "Climate management platform automating carbon accounting aligned with GHG Protocol for enterprises and asset managers.",
    websiteUrl: "https://persefoni.com",
    category: "CARBON_MANAGEMENT",
    subcategories: ["Carbon Accounting", "Climate Disclosure", "Financed Emissions", "GHG Reporting"],
    pricingModel: "SUBSCRIPTION",
    hasFreeTrialOrTier: true,
    frameworksSupported: ["GHG Protocol", "CDP", "TCFD", "CSRD", "SEC Climate Rule", "PCAF", "SBTi"],
    deploymentsSupported: ["Cloud"],
    integrationsSupported: ["SAP", "Oracle", "Workday", "Salesforce", "Microsoft 365"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: false,
    overallScore: 8.5,
    easeOfUse: 8.5,
    featureRichness: 8.5,
    valueForMoney: 7.5,
    customerSupport: 8.0,
    keyFeatures: ["Automated carbon accounting", "Scope 1/2/3 emissions tracking", "Financed emissions (PCAF)", "Climate disclosure reporting", "Scenario analysis", "Reduction pathway planning", "Audit-grade data lineage"],
    companySize: "Enterprise",
    foundedYear: 2020,
    headquarters: "Tempe, AZ",
    employeeCount: "201-500",
    isPublished: true,
    isFeatured: true,
  },
  {
    name: "Watershed",
    slug: "watershed",
    description: "Watershed is a corporate climate platform that helps companies measure their carbon footprint, set reduction targets, and report on progress. The platform provides enterprise-grade carbon accounting with automated data ingestion, supplier engagement tools, and support for all major disclosure frameworks. Watershed serves major companies including Airbnb, Spotify, and Stripe and has raised over $100M in venture funding.",
    shortDescription: "Enterprise climate platform used by Airbnb, Spotify, and Stripe for carbon measurement and reduction planning.",
    websiteUrl: "https://watershed.com",
    category: "CARBON_MANAGEMENT",
    subcategories: ["Carbon Accounting", "Supplier Engagement", "Climate Reporting", "Decarbonization Planning"],
    pricingModel: "CONTACT_SALES",
    hasFreeTrialOrTier: false,
    frameworksSupported: ["GHG Protocol", "CDP", "TCFD", "CSRD", "SEC Climate Rule", "SBTi"],
    deploymentsSupported: ["Cloud"],
    integrationsSupported: ["SAP", "Oracle", "NetSuite", "QuickBooks", "Expensify", "AWS"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: false,
    overallScore: 8.5,
    easeOfUse: 9.0,
    featureRichness: 8.5,
    valueForMoney: 7.0,
    customerSupport: 8.5,
    keyFeatures: ["Automated carbon accounting", "Scope 1/2/3 measurement", "Supplier engagement tools", "Clean power procurement", "Climate disclosure reporting", "Reduction scenario modeling", "Carbon credit marketplace"],
    companySize: "Enterprise",
    foundedYear: 2019,
    headquarters: "San Francisco, CA",
    employeeCount: "201-500",
    isPublished: true,
    isFeatured: true,
  },
  {
    name: "Diligent ESG",
    slug: "diligent-esg",
    description: "Diligent ESG (formerly Accuvio) is part of Diligent Corporation's modern governance platform, providing ESG data management, reporting, and board-level governance tools. The platform helps organizations collect ESG data from across the enterprise, track performance against targets, and generate reports aligned with major frameworks. Diligent serves over 25,000 organizations globally with its combined governance, risk, compliance, and ESG solutions.",
    shortDescription: "ESG and governance platform within Diligent's suite serving 25,000+ organizations for board-level ESG reporting.",
    websiteUrl: "https://www.diligent.com/solutions/esg",
    category: "ESG_REPORTING",
    subcategories: ["ESG Reporting", "Board Governance", "ESG Data Management", "Compliance"],
    pricingModel: "CONTACT_SALES",
    hasFreeTrialOrTier: false,
    frameworksSupported: ["GRI", "SASB", "TCFD", "CDP", "CSRD", "EU Taxonomy", "UN SDGs"],
    deploymentsSupported: ["Cloud"],
    integrationsSupported: ["SAP", "Oracle", "Microsoft 365", "Workday", "Power BI"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: true,
    overallScore: 8.2,
    easeOfUse: 7.5,
    featureRichness: 8.5,
    valueForMoney: 7.0,
    customerSupport: 8.0,
    keyFeatures: ["ESG data collection & aggregation", "Multi-framework reporting", "Board-level dashboards", "Target tracking & benchmarking", "Supply chain ESG assessment", "Audit trail & controls", "Stakeholder engagement tools"],
    companySize: "Enterprise",
    foundedYear: 2001,
    headquarters: "New York, NY",
    employeeCount: "1,001-5,000",
    isPublished: true,
    isFeatured: false,
  },
  {
    name: "Sphera",
    slug: "sphera",
    description: "Sphera is a leading provider of integrated risk management software focusing on Environment, Health, Safety & Sustainability (EHS&S). The platform combines operational risk management, product stewardship, and ESG solutions into a unified system. Sphera serves over 3,000 customers in 70+ countries, providing lifecycle assessment (LCA) databases and tools used globally for environmental impact measurement and reporting.",
    shortDescription: "Integrated risk management platform combining EHS, operational risk, and ESG solutions for 3,000+ customers.",
    websiteUrl: "https://sphera.com",
    category: "SUSTAINABILITY_MANAGEMENT",
    subcategories: ["EHS Management", "Operational Risk", "Product Stewardship", "LCA"],
    pricingModel: "ENTERPRISE_ONLY",
    hasFreeTrialOrTier: false,
    frameworksSupported: ["GRI", "CSRD", "EU Taxonomy", "ISO 14001", "ISO 45001", "REACH", "GHS"],
    deploymentsSupported: ["Cloud", "On-Premise"],
    integrationsSupported: ["SAP", "Oracle", "Microsoft Dynamics", "Power BI"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: true,
    overallScore: 8.0,
    easeOfUse: 7.0,
    featureRichness: 8.5,
    valueForMoney: 7.0,
    customerSupport: 7.5,
    keyFeatures: ["Lifecycle assessment (LCA)", "EHS management", "Operational risk management", "Product stewardship & compliance", "Carbon & energy management", "Supply chain sustainability", "Incident management"],
    companySize: "Enterprise",
    foundedYear: 2016,
    headquarters: "Chicago, IL",
    employeeCount: "1,001-5,000",
    isPublished: true,
    isFeatured: false,
  },
  {
    name: "EcoVadis",
    slug: "ecovadis",
    description: "EcoVadis is the world's most trusted provider of business sustainability ratings, assessing over 130,000 companies across 220 industries and 180 countries. The platform evaluates companies on Environment, Labor & Human Rights, Ethics, and Sustainable Procurement, providing scorecards, benchmarks, and improvement tools. EcoVadis ratings are used by major corporations for supply chain sustainability assessment and procurement decisions.",
    shortDescription: "World's largest sustainability ratings platform assessing 130,000+ companies across 180 countries.",
    websiteUrl: "https://ecovadis.com",
    category: "SUSTAINABILITY_MANAGEMENT",
    subcategories: ["Sustainability Ratings", "Supply Chain Assessment", "CSR Reporting", "Procurement"],
    pricingModel: "SUBSCRIPTION",
    hasFreeTrialOrTier: false,
    frameworksSupported: ["GRI", "UN Global Compact", "ISO 14001", "ISO 26000", "CDP", "UN SDGs"],
    deploymentsSupported: ["Cloud"],
    integrationsSupported: ["SAP Ariba", "Coupa", "Jaggaer", "Ivalua", "GEP"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: false,
    iso27001Certified: true,
    overallScore: 8.5,
    easeOfUse: 8.0,
    featureRichness: 8.5,
    valueForMoney: 7.5,
    customerSupport: 8.0,
    keyFeatures: ["Sustainability scorecards", "130,000+ company assessments", "Supply chain risk mapping", "Carbon action module", "Corrective action plans", "Benchmarking & analytics", "Procurement integration"],
    companySize: "Enterprise",
    foundedYear: 2007,
    headquarters: "Paris, France",
    employeeCount: "1,001-5,000",
    isPublished: true,
    isFeatured: true,
  },
  {
    name: "Novisto",
    slug: "novisto",
    description: "Novisto is an ESG data management and reporting platform designed for large enterprises. The platform centralizes ESG data collection, automates disclosure preparation, and provides analytics to track sustainability performance. Novisto supports multiple reporting frameworks simultaneously and uses AI to streamline data collection from disparate sources. The company focuses on enterprise customers in heavily regulated industries.",
    shortDescription: "Enterprise ESG data management platform centralizing sustainability data collection and multi-framework reporting.",
    websiteUrl: "https://novisto.com",
    category: "ESG_REPORTING",
    subcategories: ["ESG Data Management", "Sustainability Reporting", "ESG Analytics"],
    pricingModel: "CONTACT_SALES",
    hasFreeTrialOrTier: false,
    frameworksSupported: ["GRI", "SASB", "TCFD", "CDP", "CSRD", "EU Taxonomy", "ISSB"],
    deploymentsSupported: ["Cloud"],
    integrationsSupported: ["SAP", "Oracle", "Microsoft 365", "Power BI", "Tableau"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: false,
    overallScore: 7.8,
    easeOfUse: 8.0,
    featureRichness: 8.0,
    valueForMoney: 7.5,
    customerSupport: 8.0,
    keyFeatures: ["Centralized ESG data hub", "Multi-framework reporting", "AI-assisted data collection", "Performance benchmarking", "Materiality assessment", "Audit trail & controls", "ESG analytics dashboards"],
    companySize: "Enterprise",
    foundedYear: 2019,
    headquarters: "Montreal, Canada",
    employeeCount: "51-200",
    isPublished: true,
    isFeatured: false,
  },
  {
    name: "Plan A",
    slug: "plan-a",
    description: "Plan A is a Berlin-based carbon management and ESG reporting platform that helps companies measure, reduce, and report on their environmental impact. The platform provides automated carbon footprint calculations, science-based target setting, decarbonization action plans, and regulatory reporting aligned with CSRD, CDP, and other frameworks. Plan A serves mid-market and enterprise customers across Europe and globally.",
    shortDescription: "European carbon management and ESG reporting platform with automated calculations and CSRD-ready reporting.",
    websiteUrl: "https://plana.earth",
    category: "CARBON_MANAGEMENT",
    subcategories: ["Carbon Accounting", "ESG Reporting", "Decarbonization Planning", "CSRD Compliance"],
    pricingModel: "SUBSCRIPTION",
    hasFreeTrialOrTier: true,
    frameworksSupported: ["GHG Protocol", "CDP", "CSRD", "EU Taxonomy", "SBTi", "GRI", "TCFD"],
    deploymentsSupported: ["Cloud"],
    integrationsSupported: ["SAP", "Microsoft 365", "Google Workspace", "Xero", "QuickBooks"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: false,
    iso27001Certified: true,
    overallScore: 7.8,
    easeOfUse: 8.5,
    featureRichness: 8.0,
    valueForMoney: 8.0,
    customerSupport: 7.5,
    keyFeatures: ["Automated carbon footprint calculation", "Science-based target setting", "Decarbonization action plans", "CSRD-ready reporting", "Supplier emissions tracking", "Carbon offsetting marketplace", "Regulatory compliance dashboard"],
    companySize: "Mid-Market",
    foundedYear: 2017,
    headquarters: "Berlin, Germany",
    employeeCount: "101-200",
    isPublished: true,
    isFeatured: false,
  },

  // ============================================
  // FINTECH & REGTECH (8 vendors)
  // ============================================
  {
    name: "ComplyAdvantage",
    slug: "complyadvantage",
    description: "ComplyAdvantage is an AI-driven financial crime detection company providing real-time AML data, sanctions screening, and transaction monitoring. The platform uses machine learning and natural language processing to analyze millions of data points from sanctions lists, watchlists, PEP databases, and adverse media sources. ComplyAdvantage serves over 1,000 financial institutions, fintechs, and crypto companies globally.",
    shortDescription: "AI-driven AML and financial crime detection platform serving 1,000+ financial institutions with real-time screening.",
    websiteUrl: "https://complyadvantage.com",
    category: "AML_KYC",
    subcategories: ["AML Screening", "Sanctions Monitoring", "Transaction Monitoring", "Adverse Media"],
    pricingModel: "USAGE_BASED",
    hasFreeTrialOrTier: true,
    frameworksSupported: ["AML/BSA", "FATF", "EU AMLD", "UK MLR", "OFAC", "FinCEN"],
    deploymentsSupported: ["Cloud"],
    integrationsSupported: ["Salesforce", "Alloy", "Unit21", "Onfido", "Plaid", "Stripe"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: true,
    overallScore: 8.5,
    easeOfUse: 8.5,
    featureRichness: 8.5,
    valueForMoney: 8.0,
    customerSupport: 8.0,
    keyFeatures: ["Real-time sanctions screening", "AI-powered adverse media monitoring", "PEP database screening", "Transaction monitoring", "Customer risk scoring", "Case management", "Ongoing monitoring"],
    companySize: "Mid-Market",
    foundedYear: 2014,
    headquarters: "London, UK",
    employeeCount: "501-1,000",
    isPublished: true,
    isFeatured: true,
  },
  {
    name: "Chainalysis",
    slug: "chainalysis",
    description: "Chainalysis is the leading blockchain data and analytics company providing cryptocurrency investigation, compliance, and risk management tools. The platform is used by over 100 government agencies and 1,800+ businesses across 70 countries to trace cryptocurrency transactions, identify illicit activity, and ensure regulatory compliance. Chainalysis has played a key role in some of the largest cryptocurrency investigations globally.",
    shortDescription: "Leading blockchain analytics platform used by 100+ government agencies and 1,800+ businesses for crypto compliance.",
    websiteUrl: "https://www.chainalysis.com",
    category: "CRYPTO_COMPLIANCE",
    subcategories: ["Blockchain Analytics", "Crypto Investigation", "Transaction Monitoring", "Sanctions Compliance"],
    pricingModel: "CONTACT_SALES",
    hasFreeTrialOrTier: true,
    frameworksSupported: ["FATF Travel Rule", "AML/BSA", "OFAC", "EU AMLD", "MiCA"],
    deploymentsSupported: ["Cloud"],
    integrationsSupported: ["Coinbase", "Binance", "Kraken", "Circle", "Fireblocks", "Elliptic"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: true,
    overallScore: 9.0,
    easeOfUse: 8.0,
    featureRichness: 9.5,
    valueForMoney: 7.0,
    customerSupport: 8.5,
    keyFeatures: ["Blockchain transaction tracing", "KYT (Know Your Transaction)", "Sanctions screening", "Investigation tools (Reactor)", "Market intelligence", "DeFi risk assessment", "Cross-chain analysis"],
    companySize: "Enterprise",
    foundedYear: 2014,
    headquarters: "New York, NY",
    employeeCount: "501-1,000",
    isPublished: true,
    isFeatured: true,
  },
  {
    name: "Sumsub",
    slug: "sumsub",
    description: "Sumsub is an all-in-one identity verification and compliance platform that provides KYC, KYB, AML screening, and transaction monitoring in a single solution. The platform supports over 14,000 document types from 220+ countries and uses AI to automate identity verification in seconds. Sumsub serves over 2,000 clients including fintech companies, crypto exchanges, and online marketplaces.",
    shortDescription: "All-in-one identity verification platform supporting 14,000+ document types from 220+ countries for KYC and AML.",
    websiteUrl: "https://sumsub.com",
    category: "AML_KYC",
    subcategories: ["Identity Verification", "KYC", "KYB", "AML Screening", "Fraud Prevention"],
    pricingModel: "USAGE_BASED",
    hasFreeTrialOrTier: true,
    frameworksSupported: ["AML/BSA", "FATF", "EU AMLD", "UK MLR", "MiCA", "GDPR"],
    deploymentsSupported: ["Cloud"],
    integrationsSupported: ["Stripe", "Salesforce", "HubSpot", "Zendesk", "Slack"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: true,
    overallScore: 8.3,
    easeOfUse: 9.0,
    featureRichness: 8.5,
    valueForMoney: 8.5,
    customerSupport: 8.0,
    keyFeatures: ["AI-powered identity verification", "Document verification (14,000+ types)", "Liveness detection", "AML/PEP screening", "KYB business verification", "Transaction monitoring", "Risk-based workflows"],
    companySize: "Mid-Market",
    foundedYear: 2015,
    headquarters: "London, UK",
    employeeCount: "501-1,000",
    isPublished: true,
    isFeatured: false,
  },
  {
    name: "NICE Actimize",
    slug: "nice-actimize",
    description: "NICE Actimize is the largest and broadest provider of financial crime, risk, and compliance solutions for financial institutions. A division of NICE Ltd (NASDAQ: NICE), the platform provides enterprise-grade anti-money laundering, fraud prevention, sanctions screening, and market surveillance solutions. NICE Actimize serves over 100 of the world's top financial institutions, processing billions of transactions to detect financial crime.",
    shortDescription: "Largest financial crime and compliance solution provider serving 100+ top global financial institutions.",
    websiteUrl: "https://www.niceactimize.com",
    category: "TRANSACTION_MONITORING",
    subcategories: ["AML", "Fraud Detection", "Sanctions Screening", "Market Surveillance"],
    pricingModel: "ENTERPRISE_ONLY",
    hasFreeTrialOrTier: false,
    frameworksSupported: ["AML/BSA", "FATF", "EU AMLD", "MiFID II", "Dodd-Frank", "MAR"],
    deploymentsSupported: ["Cloud", "On-Premise", "Hybrid"],
    integrationsSupported: ["FIS", "Temenos", "Finastra", "Jack Henry", "Core banking systems"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: true,
    overallScore: 9.0,
    easeOfUse: 6.5,
    featureRichness: 9.5,
    valueForMoney: 6.5,
    customerSupport: 8.0,
    keyFeatures: ["Enterprise AML detection", "Real-time fraud prevention", "Sanctions screening", "Market surveillance", "Customer due diligence", "SAR/STR filing", "AI-driven alert prioritization"],
    companySize: "Enterprise",
    foundedYear: 1999,
    headquarters: "Hoboken, NJ",
    employeeCount: "1,001-5,000",
    isPublished: true,
    isFeatured: true,
  },
  {
    name: "Refinitiv (LSEG)",
    slug: "refinitiv-lseg",
    description: "Refinitiv, now part of London Stock Exchange Group (LSEG), provides one of the world's largest financial compliance data sets including World-Check for KYC and third-party risk screening. The platform covers sanctions, PEP, and adverse media data on over 5.4 million entities, serving financial institutions, corporates, and government agencies. Refinitiv's compliance solutions are the industry standard for customer due diligence.",
    shortDescription: "LSEG-owned financial compliance data platform with World-Check screening over 5.4 million entities globally.",
    websiteUrl: "https://www.lseg.com/en/data-analytics/financial-data",
    category: "REGTECH",
    subcategories: ["KYC Screening", "Risk Intelligence", "Sanctions Data", "Due Diligence"],
    pricingModel: "ENTERPRISE_ONLY",
    hasFreeTrialOrTier: false,
    frameworksSupported: ["AML/BSA", "FATF", "EU AMLD", "OFAC", "UK MLR", "MiFID II"],
    deploymentsSupported: ["Cloud", "On-Premise"],
    integrationsSupported: ["FIS", "Temenos", "Finastra", "SAP", "Oracle"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: true,
    overallScore: 9.0,
    easeOfUse: 7.0,
    featureRichness: 9.5,
    valueForMoney: 6.5,
    customerSupport: 8.0,
    keyFeatures: ["World-Check risk intelligence", "5.4M+ entity database", "Sanctions screening", "PEP identification", "Adverse media monitoring", "Enhanced due diligence reports", "API & batch screening"],
    companySize: "Enterprise",
    foundedYear: 2018,
    headquarters: "London, UK",
    employeeCount: "10,000+",
    isPublished: true,
    isFeatured: true,
  },
  {
    name: "Featurespace",
    slug: "featurespace",
    description: "Featurespace is a Cambridge University spin-out that developed the ARIC Risk Hub, an adaptive behavioral analytics platform for fraud and financial crime detection. The platform uses machine learning to analyze customer behavior in real-time, detecting anomalies without relying on rules or historical fraud labels. Featurespace serves major banks, payment processors, and fintechs including HSBC, NatWest, and Worldpay.",
    shortDescription: "Adaptive behavioral analytics platform for real-time fraud detection, spun out of Cambridge University.",
    websiteUrl: "https://www.featurespace.com",
    category: "TRANSACTION_MONITORING",
    subcategories: ["Fraud Detection", "Behavioral Analytics", "Payment Fraud", "AML"],
    pricingModel: "CONTACT_SALES",
    hasFreeTrialOrTier: false,
    frameworksSupported: ["AML/BSA", "PSD2", "EU AMLD", "UK MLR", "FATF"],
    deploymentsSupported: ["Cloud", "On-Premise"],
    integrationsSupported: ["FIS", "Temenos", "Finastra", "Mastercard", "Visa"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: true,
    overallScore: 8.3,
    easeOfUse: 7.0,
    featureRichness: 8.5,
    valueForMoney: 7.5,
    customerSupport: 8.0,
    keyFeatures: ["Adaptive behavioral analytics", "Real-time fraud detection", "Anomaly detection without labels", "Payment fraud prevention", "AML transaction monitoring", "Risk scoring engine", "Explainable AI models"],
    companySize: "Mid-Market",
    foundedYear: 2008,
    headquarters: "Cambridge, UK",
    employeeCount: "201-500",
    isPublished: true,
    isFeatured: false,
  },
  {
    name: "Alloy",
    slug: "alloy",
    description: "Alloy is an identity decisioning platform that helps banks and fintechs automate their onboarding, compliance, and fraud prevention workflows. The platform orchestrates data from over 200 identity verification, compliance, and fraud detection sources into a single decision engine. Alloy serves over 600 financial institutions including major banks and fast-growing fintechs, automating millions of identity decisions.",
    shortDescription: "Identity decisioning platform orchestrating 200+ data sources for automated onboarding and compliance at 600+ banks.",
    websiteUrl: "https://www.alloy.com",
    category: "AML_KYC",
    subcategories: ["Identity Verification", "KYC", "Fraud Prevention", "Compliance Automation"],
    pricingModel: "USAGE_BASED",
    hasFreeTrialOrTier: false,
    frameworksSupported: ["AML/BSA", "FATF", "CIP", "CDD", "OFAC"],
    deploymentsSupported: ["Cloud"],
    integrationsSupported: ["Plaid", "Socure", "ComplyAdvantage", "Experian", "TransUnion", "Equifax"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: false,
    overallScore: 8.5,
    easeOfUse: 8.5,
    featureRichness: 8.5,
    valueForMoney: 8.0,
    customerSupport: 8.5,
    keyFeatures: ["Identity decisioning engine", "200+ data source orchestration", "Automated KYC/KYB workflows", "Fraud detection", "Ongoing monitoring", "No-code journey builder", "Case management"],
    companySize: "Mid-Market",
    foundedYear: 2015,
    headquarters: "New York, NY",
    employeeCount: "201-500",
    isPublished: true,
    isFeatured: true,
  },
  {
    name: "Unit21",
    slug: "unit21",
    description: "Unit21 is a no-code compliance infrastructure platform that helps fintechs, banks, and crypto companies detect and investigate financial crime. The platform provides transaction monitoring, case management, SAR/STR filing, and KYC orchestration through a flexible, rules-based and ML-powered engine. Unit21 enables compliance teams to build and modify detection rules without engineering resources.",
    shortDescription: "No-code compliance infrastructure for transaction monitoring and financial crime detection at fintechs and banks.",
    websiteUrl: "https://www.unit21.ai",
    category: "TRANSACTION_MONITORING",
    subcategories: ["Transaction Monitoring", "Case Management", "KYC", "Fraud Detection"],
    pricingModel: "USAGE_BASED",
    hasFreeTrialOrTier: true,
    frameworksSupported: ["AML/BSA", "FATF", "FinCEN", "OFAC", "EU AMLD"],
    deploymentsSupported: ["Cloud"],
    integrationsSupported: ["Plaid", "Alloy", "Stripe", "Marqeta", "Galileo", "Sardine"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: false,
    overallScore: 8.2,
    easeOfUse: 9.0,
    featureRichness: 8.0,
    valueForMoney: 8.5,
    customerSupport: 8.5,
    keyFeatures: ["No-code rule builder", "Transaction monitoring", "Case management & investigation", "SAR/STR filing automation", "KYC/KYB orchestration", "ML-powered detection", "Real-time alerting"],
    companySize: "Startup",
    foundedYear: 2018,
    headquarters: "San Francisco, CA",
    employeeCount: "101-200",
    isPublished: true,
    isFeatured: false,
  },

  // ============================================
  // HR & EMPLOYMENT COMPLIANCE (8 vendors)
  // ============================================
  {
    name: "Deel",
    slug: "deel",
    description: "Deel is the leading global HR and payroll platform enabling companies to hire, pay, and manage workers in over 150 countries. The platform provides employer of record (EOR) services, contractor management, global payroll, and built-in compliance with local labor laws, tax regulations, and employment standards. Deel has grown to serve over 35,000 customers and achieved a $12 billion valuation, making it one of the most valuable HR tech companies.",
    shortDescription: "Leading global HR platform for hiring and paying workers in 150+ countries with built-in local compliance.",
    websiteUrl: "https://www.deel.com",
    category: "HR_COMPLIANCE",
    subcategories: ["Global Payroll", "Employer of Record", "Contractor Management", "Immigration"],
    pricingModel: "PER_SEAT",
    hasFreeTrialOrTier: true,
    frameworksSupported: ["Local Labor Laws (150+ countries)", "GDPR", "SOX", "FLSA"],
    deploymentsSupported: ["Cloud"],
    integrationsSupported: ["QuickBooks", "Xero", "NetSuite", "BambooHR", "Greenhouse", "Ashby", "Slack"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: true,
    overallScore: 9.0,
    easeOfUse: 9.0,
    featureRichness: 9.0,
    valueForMoney: 8.0,
    customerSupport: 8.5,
    keyFeatures: ["Employer of Record (EOR) in 150+ countries", "Global payroll processing", "Contractor management & payments", "Automated compliance with local laws", "Immigration & visa support", "Equipment management", "HR & benefits administration"],
    companySize: "Mid-Market",
    foundedYear: 2019,
    headquarters: "San Francisco, CA",
    employeeCount: "1,001-5,000",
    isPublished: true,
    isFeatured: true,
  },
  {
    name: "Rippling",
    slug: "rippling",
    description: "Rippling is a unified workforce management platform that combines HR, IT, and Finance into a single system. The platform provides payroll, benefits, device management, app management, and compliance tools, automating the administrative work of managing employees. Rippling serves over 10,000 customers and has been valued at over $13 billion, offering built-in compliance features for tax filing, ACA reporting, and labor law adherence.",
    shortDescription: "Unified workforce management platform combining HR, IT, and Finance with automated compliance across all 50 states.",
    websiteUrl: "https://www.rippling.com",
    category: "HR_COMPLIANCE",
    subcategories: ["HR Platform", "Payroll", "IT Management", "Benefits Administration"],
    pricingModel: "PER_SEAT",
    hasFreeTrialOrTier: false,
    frameworksSupported: ["FLSA", "ACA", "ERISA", "State Labor Laws", "GDPR", "SOX"],
    deploymentsSupported: ["Cloud"],
    integrationsSupported: ["Slack", "Microsoft 365", "Google Workspace", "QuickBooks", "Greenhouse", "Lever", "Jira"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: false,
    overallScore: 9.0,
    easeOfUse: 9.5,
    featureRichness: 9.0,
    valueForMoney: 8.5,
    customerSupport: 8.0,
    keyFeatures: ["Unified HR, IT & Finance platform", "Automated tax filing (all 50 states)", "Benefits administration & compliance", "Device & app management", "Workflow automation", "ACA & COBRA compliance", "Global payroll"],
    companySize: "Mid-Market",
    foundedYear: 2016,
    headquarters: "San Francisco, CA",
    employeeCount: "1,001-5,000",
    isPublished: true,
    isFeatured: true,
  },
  {
    name: "Papaya Global",
    slug: "papaya-global",
    description: "Papaya Global is a global payroll and payments platform that provides automated payroll processing, compliance management, and workforce payments in over 160 countries. The platform uses AI to ensure compliance with local tax codes, social contributions, and labor regulations. Papaya Global has built its own payments infrastructure and holds financial licenses, enabling direct payroll payments to employees worldwide.",
    shortDescription: "Global payroll and payments platform with AI-driven compliance across 160+ countries and proprietary payment rails.",
    websiteUrl: "https://www.papayaglobal.com",
    category: "HR_COMPLIANCE",
    subcategories: ["Global Payroll", "Payments", "Compliance Automation", "EOR"],
    pricingModel: "PER_SEAT",
    hasFreeTrialOrTier: false,
    frameworksSupported: ["Local Labor Laws (160+ countries)", "GDPR", "SOX", "FLSA"],
    deploymentsSupported: ["Cloud"],
    integrationsSupported: ["SAP SuccessFactors", "Workday", "NetSuite", "BambooHR", "Microsoft Dynamics"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: true,
    overallScore: 8.3,
    easeOfUse: 8.0,
    featureRichness: 8.5,
    valueForMoney: 7.5,
    customerSupport: 8.0,
    keyFeatures: ["Global payroll in 160+ countries", "Proprietary payment infrastructure", "AI-driven compliance engine", "EOR services", "Workforce analytics", "Cross-border payments", "Tax & social contribution management"],
    companySize: "Mid-Market",
    foundedYear: 2016,
    headquarters: "New York, NY",
    employeeCount: "501-1,000",
    isPublished: true,
    isFeatured: false,
  },
  {
    name: "Remote.com",
    slug: "remote-com",
    description: "Remote.com is a global employment platform that helps companies hire, manage, and pay employees and contractors worldwide. The platform provides employer of record services, contractor management, global payroll, and benefits in over 70 countries with owned legal entities (not third-party partners). Remote focuses on IP protection, compliance with local employment laws, and providing equity incentives across borders.",
    shortDescription: "Global employment platform with owned entities in 70+ countries for compliant hiring, payroll, and benefits.",
    websiteUrl: "https://remote.com",
    category: "HR_COMPLIANCE",
    subcategories: ["Employer of Record", "Global Payroll", "Contractor Management", "Benefits"],
    pricingModel: "PER_SEAT",
    hasFreeTrialOrTier: true,
    frameworksSupported: ["Local Labor Laws (70+ countries)", "GDPR", "IP Protection Laws"],
    deploymentsSupported: ["Cloud"],
    integrationsSupported: ["BambooHR", "Greenhouse", "HiBob", "Lever", "QuickBooks", "Xero"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: true,
    overallScore: 8.2,
    easeOfUse: 8.5,
    featureRichness: 8.0,
    valueForMoney: 8.5,
    customerSupport: 8.0,
    keyFeatures: ["Owned legal entities (not third-party)", "EOR in 70+ countries", "Global payroll processing", "Contractor management", "Equity incentive management", "IP protection & assignment", "Benefits administration"],
    companySize: "Mid-Market",
    foundedYear: 2019,
    headquarters: "San Francisco, CA",
    employeeCount: "1,001-5,000",
    isPublished: true,
    isFeatured: false,
  },
  {
    name: "Oyster HR",
    slug: "oyster-hr",
    description: "Oyster HR is a global employment platform designed for distributed teams, providing hiring, payroll, benefits, and compliance in over 180 countries. The platform automates employment contracts, ensures local law compliance, and manages global payroll and benefits. Oyster is a certified B Corporation and focuses on making global employment accessible and equitable, serving companies from startups to enterprises.",
    shortDescription: "B Corp-certified global employment platform enabling compliant distributed hiring across 180+ countries.",
    websiteUrl: "https://www.oysterhr.com",
    category: "HR_COMPLIANCE",
    subcategories: ["Employer of Record", "Global Payroll", "Distributed Workforce", "Benefits"],
    pricingModel: "PER_SEAT",
    hasFreeTrialOrTier: true,
    frameworksSupported: ["Local Labor Laws (180+ countries)", "GDPR", "Equal Pay Regulations"],
    deploymentsSupported: ["Cloud"],
    integrationsSupported: ["Greenhouse", "Lever", "BambooHR", "QuickBooks", "Xero", "Slack"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: false,
    overallScore: 8.0,
    easeOfUse: 8.5,
    featureRichness: 7.5,
    valueForMoney: 8.0,
    customerSupport: 8.0,
    keyFeatures: ["EOR in 180+ countries", "Automated employment contracts", "Local compliance engine", "Global payroll", "Benefits management", "Time-off management", "Compensation benchmarking"],
    companySize: "SMB",
    foundedYear: 2020,
    headquarters: "Remote-first (US incorporated)",
    employeeCount: "501-1,000",
    isPublished: true,
    isFeatured: false,
  },
  {
    name: "Trusaic",
    slug: "trusaic",
    description: "Trusaic is a workforce analytics and compliance platform specializing in pay equity analysis, ACA compliance, and workforce intelligence. The platform helps organizations identify and address pay disparities based on gender, race, ethnicity, and other protected characteristics. Trusaic's analytics engine supports proactive pay equity audits required by emerging legislation in states like California, Colorado, and Illinois, as well as the EU Pay Transparency Directive.",
    shortDescription: "Pay equity and workforce compliance analytics platform supporting emerging equal pay legislation globally.",
    websiteUrl: "https://trusaic.com",
    category: "PAY_EQUITY",
    subcategories: ["Pay Equity Analytics", "ACA Compliance", "Workforce Intelligence", "DE&I Analytics"],
    pricingModel: "SUBSCRIPTION",
    hasFreeTrialOrTier: false,
    frameworksSupported: ["Equal Pay Act", "CA SB 1162", "EU Pay Transparency Directive", "ACA", "OFCCP"],
    deploymentsSupported: ["Cloud"],
    integrationsSupported: ["Workday", "ADP", "UKG", "SAP SuccessFactors", "Paylocity"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: false,
    overallScore: 8.0,
    easeOfUse: 8.0,
    featureRichness: 8.0,
    valueForMoney: 8.0,
    customerSupport: 8.0,
    keyFeatures: ["Pay equity analysis", "ACA compliance automation", "Pay gap identification", "Remediation modeling", "Legislative tracking", "Workforce analytics", "Compensation benchmarking"],
    companySize: "Mid-Market",
    foundedYear: 2017,
    headquarters: "Los Angeles, CA",
    employeeCount: "201-500",
    isPublished: true,
    isFeatured: true,
  },
  {
    name: "Syndio",
    slug: "syndio",
    description: "Syndio is a workplace equity analytics platform that helps companies measure, resolve, and prevent pay and opportunity gaps. The platform provides continuous monitoring of pay equity, hiring equity, and opportunity equity using statistical analysis and machine learning. Syndio is trusted by over 300 companies including major enterprises and has been recognized as one of the most impactful workplace equity solutions available.",
    shortDescription: "Workplace equity analytics platform for continuous monitoring of pay, hiring, and opportunity gaps across 300+ companies.",
    websiteUrl: "https://synd.io",
    category: "PAY_EQUITY",
    subcategories: ["Pay Equity", "Hiring Equity", "Opportunity Equity", "DE&I Analytics"],
    pricingModel: "CONTACT_SALES",
    hasFreeTrialOrTier: false,
    frameworksSupported: ["Equal Pay Act", "CA SB 1162", "EU Pay Transparency Directive", "OFCCP", "Title VII"],
    deploymentsSupported: ["Cloud"],
    integrationsSupported: ["Workday", "SAP SuccessFactors", "ADP", "UKG", "Oracle HCM"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: false,
    overallScore: 8.5,
    easeOfUse: 8.0,
    featureRichness: 8.5,
    valueForMoney: 7.5,
    customerSupport: 8.5,
    keyFeatures: ["Pay equity analysis", "Hiring equity monitoring", "Opportunity equity tracking", "Statistical regression modeling", "Remediation recommendations", "Continuous monitoring", "Board-ready reporting"],
    companySize: "Mid-Market",
    foundedYear: 2017,
    headquarters: "Seattle, WA",
    employeeCount: "201-500",
    isPublished: true,
    isFeatured: true,
  },
  {
    name: "BambooHR",
    slug: "bamboohr",
    description: "BambooHR is a leading cloud-based HR platform designed for small and medium-sized businesses, providing core HR, payroll, benefits, hiring, and compliance tools. The platform helps SMBs manage employee records, automate onboarding, track time off, and maintain compliance with federal and state employment laws. BambooHR serves over 33,000 customers and is known for its user-friendly interface and strong customer satisfaction.",
    shortDescription: "SMB-focused HR platform serving 33,000+ customers with payroll, benefits, hiring, and compliance tools.",
    websiteUrl: "https://www.bamboohr.com",
    category: "HR_COMPLIANCE",
    subcategories: ["HR Platform", "Payroll", "Benefits", "Hiring", "Compliance"],
    pricingModel: "PER_SEAT",
    hasFreeTrialOrTier: true,
    frameworksSupported: ["FLSA", "ACA", "EEO-1", "State Labor Laws", "FMLA"],
    deploymentsSupported: ["Cloud"],
    integrationsSupported: ["Slack", "Microsoft Teams", "Google Workspace", "Greenhouse", "Indeed", "Glassdoor", "QuickBooks"],
    hasDPA: true,
    gdprCompliant: true,
    soc2Certified: true,
    iso27001Certified: false,
    overallScore: 8.3,
    easeOfUse: 9.5,
    featureRichness: 7.5,
    valueForMoney: 9.0,
    customerSupport: 9.0,
    keyFeatures: ["Core HR & employee records", "Payroll processing", "Benefits administration", "Applicant tracking", "Onboarding automation", "Time tracking & PTO", "Compliance reporting (EEO-1, ACA)"],
    companySize: "SMB",
    foundedYear: 2008,
    headquarters: "Lindon, UT",
    employeeCount: "1,001-5,000",
    isPublished: true,
    isFeatured: false,
  },
];

async function main() {
  console.log("=== Multi-Domain Vendor Seed Script ===\n");
  console.log(`Total vendors to process: ${vendors.length}\n`);

  let created = 0;
  let skipped = 0;
  let errors = 0;

  for (const vendor of vendors) {
    try {
      const existing = await prisma.vendor.findUnique({
        where: { slug: vendor.slug },
      });

      if (existing) {
        console.log(`  SKIP  ${vendor.name} (slug "${vendor.slug}" already exists)`);
        skipped++;
        continue;
      }

      await prisma.vendor.create({ data: vendor as any });
      console.log(`  CREATE  ${vendor.name} [${vendor.category}]`);
      created++;
    } catch (err: any) {
      console.error(`  ERROR  ${vendor.name}: ${err.message}`);
      errors++;
    }
  }

  console.log("\n=== Summary ===");
  console.log(`  Created: ${created}`);
  console.log(`  Skipped: ${skipped}`);
  console.log(`  Errors:  ${errors}`);
  console.log(`  Total:   ${vendors.length}`);
}

main()
  .catch((e) => {
    console.error("Fatal error:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
